// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface ASYNC_WAIT_CTX_set_wait_fd$cleanup {

    void apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, int x2, jdk.incubator.foreign.MemoryAddress x3);
    static NativeSymbol allocate(ASYNC_WAIT_CTX_set_wait_fd$cleanup fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(ASYNC_WAIT_CTX_set_wait_fd$cleanup.class, fi, constants$732.ASYNC_WAIT_CTX_set_wait_fd$cleanup$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static ASYNC_WAIT_CTX_set_wait_fd$cleanup ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("ASYNC_WAIT_CTX_set_wait_fd$cleanup::" + Long.toHexString(addr.toRawLongValue()), addr, scope);return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, int x2, jdk.incubator.foreign.MemoryAddress x3) -> {
            try {
                constants$733.ASYNC_WAIT_CTX_set_wait_fd$cleanup$MH.invokeExact(symbol, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


