// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface ASYNC_start_job$func {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static CLinker.UpcallStub allocate(ASYNC_start_job$func fi) {
        return RuntimeHelper.upcallStub(ASYNC_start_job$func.class, fi, constants$734.ASYNC_start_job$func$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
    }
    static CLinker.UpcallStub allocate(ASYNC_start_job$func fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(ASYNC_start_job$func.class, fi, constants$734.ASYNC_start_job$func$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static ASYNC_start_job$func ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$734.ASYNC_start_job$func$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


