// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface BN_GENCB_set$callback {

    int apply(int x0, int x1, jdk.incubator.foreign.MemoryAddress x2);
    static CLinker.UpcallStub allocate(BN_GENCB_set$callback fi) {
        return RuntimeHelper.upcallStub(BN_GENCB_set$callback.class, fi, constants$146.BN_GENCB_set$callback$FUNC, "(IILjdk/incubator/foreign/MemoryAddress;)I");
    }
    static CLinker.UpcallStub allocate(BN_GENCB_set$callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(BN_GENCB_set$callback.class, fi, constants$146.BN_GENCB_set$callback$FUNC, "(IILjdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static BN_GENCB_set$callback ofAddress(MemoryAddress addr) {
        return (int x0, int x1, jdk.incubator.foreign.MemoryAddress x2) -> {
            try {
                return (int)constants$146.BN_GENCB_set$callback$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


