// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface CONF_parse_list$list_cb {

    int apply(jdk.incubator.foreign.MemoryAddress x0, int x1, jdk.incubator.foreign.MemoryAddress x2);
    static CLinker.UpcallStub allocate(CONF_parse_list$list_cb fi) {
        return RuntimeHelper.upcallStub(CONF_parse_list$list_cb.class, fi, constants$927.CONF_parse_list$list_cb$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I");
    }
    static CLinker.UpcallStub allocate(CONF_parse_list$list_cb fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(CONF_parse_list$list_cb.class, fi, constants$927.CONF_parse_list$list_cb$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static CONF_parse_list$list_cb ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, int x1, jdk.incubator.foreign.MemoryAddress x2) -> {
            try {
                return (int)constants$927.CONF_parse_list$list_cb$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


