// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1281 {

    static final MemorySegment LN_iana$SEGMENT = ResourceScope.globalScope().allocateUtf8String("iana");
    static final MemorySegment SN_Directory$SEGMENT = ResourceScope.globalScope().allocateUtf8String("directory");
    static final MemorySegment LN_Directory$SEGMENT = ResourceScope.globalScope().allocateUtf8String("Directory");
    static final MemorySegment SN_Management$SEGMENT = ResourceScope.globalScope().allocateUtf8String("mgmt");
    static final MemorySegment LN_Management$SEGMENT = ResourceScope.globalScope().allocateUtf8String("Management");
    static final MemorySegment SN_Experimental$SEGMENT = ResourceScope.globalScope().allocateUtf8String("experimental");
}


