// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$430 {

    static final FunctionDescriptor d2i_RSA_PSS_PARAMS$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_RSA_PSS_PARAMS$MH = RuntimeHelper.downcallHandle(
        "d2i_RSA_PSS_PARAMS",
        constants$430.d2i_RSA_PSS_PARAMS$FUNC, false
    );
    static final FunctionDescriptor i2d_RSA_PSS_PARAMS$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_RSA_PSS_PARAMS$MH = RuntimeHelper.downcallHandle(
        "i2d_RSA_PSS_PARAMS",
        constants$430.i2d_RSA_PSS_PARAMS$FUNC, false
    );
    static final FunctionDescriptor RSA_OAEP_PARAMS_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle RSA_OAEP_PARAMS_new$MH = RuntimeHelper.downcallHandle(
        "RSA_OAEP_PARAMS_new",
        constants$430.RSA_OAEP_PARAMS_new$FUNC, false
    );
    static final FunctionDescriptor RSA_OAEP_PARAMS_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle RSA_OAEP_PARAMS_free$MH = RuntimeHelper.downcallHandle(
        "RSA_OAEP_PARAMS_free",
        constants$430.RSA_OAEP_PARAMS_free$FUNC, false
    );
    static final FunctionDescriptor d2i_RSA_OAEP_PARAMS$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_RSA_OAEP_PARAMS$MH = RuntimeHelper.downcallHandle(
        "d2i_RSA_OAEP_PARAMS",
        constants$430.d2i_RSA_OAEP_PARAMS$FUNC, false
    );
    static final FunctionDescriptor i2d_RSA_OAEP_PARAMS$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_RSA_OAEP_PARAMS$MH = RuntimeHelper.downcallHandle(
        "i2d_RSA_OAEP_PARAMS",
        constants$430.i2d_RSA_OAEP_PARAMS$FUNC, false
    );
}


