// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$601 {

    static final FunctionDescriptor sk_PKCS7_RECIP_INFO_is_sorted$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_RECIP_INFO_is_sorted$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_RECIP_INFO_is_sorted",
        constants$601.sk_PKCS7_RECIP_INFO_is_sorted$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_RECIP_INFO_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_RECIP_INFO_dup$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_RECIP_INFO_dup",
        constants$601.sk_PKCS7_RECIP_INFO_dup$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_RECIP_INFO_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_RECIP_INFO_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_RECIP_INFO_deep_copy",
        constants$601.sk_PKCS7_RECIP_INFO_deep_copy$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_RECIP_INFO_set_cmp_func$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_RECIP_INFO_set_cmp_func$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_RECIP_INFO_set_cmp_func",
        constants$601.sk_PKCS7_RECIP_INFO_set_cmp_func$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_compfunc$MH = RuntimeHelper.downcallHandle(
        constants$601.sk_PKCS7_compfunc$FUNC, false
    );
}


