// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$252 {

    static final FunctionDescriptor SMIME_write_ASN1$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SMIME_write_ASN1$MH = RuntimeHelper.downcallHandle(
        "SMIME_write_ASN1",
        constants$252.SMIME_write_ASN1$FUNC, false
    );
    static final FunctionDescriptor SMIME_read_ASN1$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SMIME_read_ASN1$MH = RuntimeHelper.downcallHandle(
        "SMIME_read_ASN1",
        constants$252.SMIME_read_ASN1$FUNC, false
    );
    static final FunctionDescriptor SMIME_crlf_copy$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle SMIME_crlf_copy$MH = RuntimeHelper.downcallHandle(
        "SMIME_crlf_copy",
        constants$252.SMIME_crlf_copy$FUNC, false
    );
    static final FunctionDescriptor SMIME_text$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SMIME_text$MH = RuntimeHelper.downcallHandle(
        "SMIME_text",
        constants$252.SMIME_text$FUNC, false
    );
    static final FunctionDescriptor ASN1_ITEM_lookup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_ITEM_lookup$MH = RuntimeHelper.downcallHandle(
        "ASN1_ITEM_lookup",
        constants$252.ASN1_ITEM_lookup$FUNC, false
    );
    static final FunctionDescriptor ASN1_ITEM_get$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle ASN1_ITEM_get$MH = RuntimeHelper.downcallHandle(
        "ASN1_ITEM_get",
        constants$252.ASN1_ITEM_get$FUNC, false
    );
}


