// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1064 {

    static final FunctionDescriptor sk_PROFESSION_INFO_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_PROFESSION_INFO_freefunc$MH = RuntimeHelper.downcallHandle(
        constants$1064.sk_PROFESSION_INFO_freefunc$FUNC, false
    );
    static final FunctionDescriptor sk_PROFESSION_INFO_copyfunc$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PROFESSION_INFO_copyfunc$MH = RuntimeHelper.downcallHandle(
        constants$1064.sk_PROFESSION_INFO_copyfunc$FUNC, false
    );
    static final FunctionDescriptor sk_PROFESSION_INFO_num$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_PROFESSION_INFO_num$MH = RuntimeHelper.downcallHandle(
        "sk_PROFESSION_INFO_num",
        constants$1064.sk_PROFESSION_INFO_num$FUNC, false
    );
    static final FunctionDescriptor sk_PROFESSION_INFO_value$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_PROFESSION_INFO_value$MH = RuntimeHelper.downcallHandle(
        "sk_PROFESSION_INFO_value",
        constants$1064.sk_PROFESSION_INFO_value$FUNC, false
    );
}


