// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1060 {

    static final FunctionDescriptor sk_ADMISSIONS_new$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_new$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_new",
        constants$1060.sk_ADMISSIONS_new$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_new_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle sk_ADMISSIONS_new_null$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_new_null",
        constants$1060.sk_ADMISSIONS_new_null$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_new_reserve$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ADMISSIONS_new_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_new_reserve",
        constants$1060.sk_ADMISSIONS_new_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ADMISSIONS_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_reserve",
        constants$1060.sk_ADMISSIONS_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_free$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_free",
        constants$1060.sk_ADMISSIONS_free$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_zero$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_zero",
        constants$1060.sk_ADMISSIONS_zero$FUNC, false
    );
}


