// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$708 {

    static final FunctionDescriptor X509_TRUST_get0_name$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_TRUST_get0_name$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_get0_name",
        constants$708.X509_TRUST_get0_name$FUNC, false
    );
    static final FunctionDescriptor X509_TRUST_get_trust$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_TRUST_get_trust$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_get_trust",
        constants$708.X509_TRUST_get_trust$FUNC, false
    );
    static final FunctionDescriptor ERR_load_PEM_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_PEM_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_PEM_strings",
        constants$708.ERR_load_PEM_strings$FUNC, false
    );
    static final FunctionDescriptor pem_password_cb$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle pem_password_cb$MH = RuntimeHelper.downcallHandle(
        constants$708.pem_password_cb$FUNC, false
    );
    static final FunctionDescriptor PEM_get_EVP_CIPHER_INFO$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_get_EVP_CIPHER_INFO$MH = RuntimeHelper.downcallHandle(
        "PEM_get_EVP_CIPHER_INFO",
        constants$708.PEM_get_EVP_CIPHER_INFO$FUNC, false
    );
}


