// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$216 {

    static final FunctionDescriptor ASN1_BIT_STRING_set_bit$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle ASN1_BIT_STRING_set_bit$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_set_bit",
        constants$216.ASN1_BIT_STRING_set_bit$FUNC, false
    );
    static final FunctionDescriptor ASN1_BIT_STRING_get_bit$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ASN1_BIT_STRING_get_bit$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_get_bit",
        constants$216.ASN1_BIT_STRING_get_bit$FUNC, false
    );
    static final FunctionDescriptor ASN1_BIT_STRING_check$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ASN1_BIT_STRING_check$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_check",
        constants$216.ASN1_BIT_STRING_check$FUNC, false
    );
    static final FunctionDescriptor ASN1_BIT_STRING_name_print$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ASN1_BIT_STRING_name_print$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_name_print",
        constants$216.ASN1_BIT_STRING_name_print$FUNC, false
    );
    static final FunctionDescriptor ASN1_BIT_STRING_num_asc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_BIT_STRING_num_asc$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_num_asc",
        constants$216.ASN1_BIT_STRING_num_asc$FUNC, false
    );
    static final FunctionDescriptor ASN1_BIT_STRING_set_asc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ASN1_BIT_STRING_set_asc$MH = RuntimeHelper.downcallHandle(
        "ASN1_BIT_STRING_set_asc",
        constants$216.ASN1_BIT_STRING_set_asc$FUNC, false
    );
}


