// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$513 {

    static final FunctionDescriptor sk_X509_REVOKED_new_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle sk_X509_REVOKED_new_null$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_new_null",
        constants$513.sk_X509_REVOKED_new_null$FUNC, false
    );
    static final FunctionDescriptor sk_X509_REVOKED_new_reserve$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_REVOKED_new_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_new_reserve",
        constants$513.sk_X509_REVOKED_new_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_X509_REVOKED_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_REVOKED_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_reserve",
        constants$513.sk_X509_REVOKED_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_X509_REVOKED_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_REVOKED_free$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_free",
        constants$513.sk_X509_REVOKED_free$FUNC, false
    );
    static final FunctionDescriptor sk_X509_REVOKED_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_REVOKED_zero$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_zero",
        constants$513.sk_X509_REVOKED_zero$FUNC, false
    );
    static final FunctionDescriptor sk_X509_REVOKED_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_REVOKED_delete$MH = RuntimeHelper.downcallHandle(
        "sk_X509_REVOKED_delete",
        constants$513.sk_X509_REVOKED_delete$FUNC, false
    );
}


