// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$318 {

    static final FunctionDescriptor EVP_add_cipher$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle EVP_add_cipher$MH = RuntimeHelper.downcallHandle(
        "EVP_add_cipher",
        constants$318.EVP_add_cipher$FUNC, false
    );
    static final FunctionDescriptor EVP_add_digest$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle EVP_add_digest$MH = RuntimeHelper.downcallHandle(
        "EVP_add_digest",
        constants$318.EVP_add_digest$FUNC, false
    );
    static final FunctionDescriptor EVP_get_cipherbyname$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_get_cipherbyname$MH = RuntimeHelper.downcallHandle(
        "EVP_get_cipherbyname",
        constants$318.EVP_get_cipherbyname$FUNC, false
    );
    static final FunctionDescriptor EVP_get_digestbyname$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_get_digestbyname$MH = RuntimeHelper.downcallHandle(
        "EVP_get_digestbyname",
        constants$318.EVP_get_digestbyname$FUNC, false
    );
    static final FunctionDescriptor EVP_CIPHER_do_all$fn$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_CIPHER_do_all$fn$MH = RuntimeHelper.downcallHandle(
        constants$318.EVP_CIPHER_do_all$fn$FUNC, false
    );
}


