// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1498 {

    static final MemorySegment TLS1_TXT_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-RSA-3DES-EDE-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-DSS-3DES-EDE-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_WITH_AES_128_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-AES-128-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_RSA_WITH_AES_128_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-RSA-AES-128-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_DSS_WITH_AES_128_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-DSS-AES-128-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_WITH_AES_256_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SRP-AES-256-CBC-SHA");
}


