// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$101 {

    static final FunctionDescriptor CRYPTO_THREAD_run_once$init$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle CRYPTO_THREAD_run_once$init$MH = RuntimeHelper.downcallHandle(
        constants$101.CRYPTO_THREAD_run_once$init$FUNC, false
    );
    static final FunctionDescriptor CRYPTO_THREAD_run_once$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle CRYPTO_THREAD_run_once$MH = RuntimeHelper.downcallHandle(
        "CRYPTO_THREAD_run_once",
        constants$101.CRYPTO_THREAD_run_once$FUNC, false
    );
    static final FunctionDescriptor CRYPTO_THREAD_init_local$cleanup$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle CRYPTO_THREAD_init_local$cleanup$MH = RuntimeHelper.downcallHandle(
        constants$101.CRYPTO_THREAD_init_local$cleanup$FUNC, false
    );
    static final FunctionDescriptor CRYPTO_THREAD_init_local$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle CRYPTO_THREAD_init_local$MH = RuntimeHelper.downcallHandle(
        "CRYPTO_THREAD_init_local",
        constants$101.CRYPTO_THREAD_init_local$FUNC, false
    );
    static final FunctionDescriptor CRYPTO_THREAD_get_local$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle CRYPTO_THREAD_get_local$MH = RuntimeHelper.downcallHandle(
        "CRYPTO_THREAD_get_local",
        constants$101.CRYPTO_THREAD_get_local$FUNC, false
    );
}


