// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1088 {

    static final FunctionDescriptor UI_method_get_flusher$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_flusher$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_flusher",
        constants$1088.UI_method_get_flusher$FUNC, false
    );
    static final FunctionDescriptor UI_method_get_reader$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_reader$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_reader",
        constants$1088.UI_method_get_reader$FUNC, false
    );
    static final FunctionDescriptor UI_method_get_closer$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_closer$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_closer",
        constants$1088.UI_method_get_closer$FUNC, false
    );
    static final FunctionDescriptor UI_method_get_prompt_constructor$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_prompt_constructor$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_prompt_constructor",
        constants$1088.UI_method_get_prompt_constructor$FUNC, false
    );
    static final FunctionDescriptor UI_method_get_data_duplicator$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_data_duplicator$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_data_duplicator",
        constants$1088.UI_method_get_data_duplicator$FUNC, false
    );
    static final FunctionDescriptor UI_method_get_data_destructor$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle UI_method_get_data_destructor$MH = RuntimeHelper.downcallHandle(
        "UI_method_get_data_destructor",
        constants$1088.UI_method_get_data_destructor$FUNC, false
    );
}


