// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$759 {

    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_find$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_find$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_find",
        constants$759.sk_SRTP_PROTECTION_PROFILE_find$FUNC, false
    );
    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_find_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_find_ex$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_find_ex",
        constants$759.sk_SRTP_PROTECTION_PROFILE_find_ex$FUNC, false
    );
    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_sort$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_sort$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_sort",
        constants$759.sk_SRTP_PROTECTION_PROFILE_sort$FUNC, false
    );
    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_is_sorted$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_is_sorted$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_is_sorted",
        constants$759.sk_SRTP_PROTECTION_PROFILE_is_sorted$FUNC, false
    );
    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_dup$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_dup",
        constants$759.sk_SRTP_PROTECTION_PROFILE_dup$FUNC, false
    );
    static final FunctionDescriptor sk_SRTP_PROTECTION_PROFILE_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SRTP_PROTECTION_PROFILE_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_SRTP_PROTECTION_PROFILE_deep_copy",
        constants$759.sk_SRTP_PROTECTION_PROFILE_deep_copy$FUNC, false
    );
}


