// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1411 {

    static final MemorySegment LN_krb5kdf$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("krb5kdf");
    static final MemorySegment SN_sskdf$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SSKDF");
    static final MemorySegment LN_sskdf$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("sskdf");
    static final MemorySegment SN_id_pkinit$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-pkinit");
    static final MemorySegment SN_pkInitClientAuth$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pkInitClientAuth");
    static final MemorySegment LN_pkInitClientAuth$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PKINIT Client Auth");
}


