// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1499 {

    static final MemorySegment TLS1_TXT_SRP_SHA_RSA_WITH_AES_256_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("SRP-RSA-AES-256-CBC-SHA");
    static final MemorySegment TLS1_TXT_SRP_SHA_DSS_WITH_AES_256_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("SRP-DSS-AES-256-CBC-SHA");
    static final MemorySegment TLS1_TXT_RSA_WITH_CAMELLIA_128_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("CAMELLIA128-SHA");
    static final MemorySegment TLS1_TXT_DH_DSS_WITH_CAMELLIA_128_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DH-DSS-CAMELLIA128-SHA");
    static final MemorySegment TLS1_TXT_DH_RSA_WITH_CAMELLIA_128_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DH-RSA-CAMELLIA128-SHA");
    static final MemorySegment TLS1_TXT_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DHE-DSS-CAMELLIA128-SHA");
}


