// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor srandom$FUNC = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle srandom$MH = RuntimeHelper.downcallHandle(
        "srandom",
        constants$5.srandom$FUNC, false
    );
    static final FunctionDescriptor initstate$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle initstate$MH = RuntimeHelper.downcallHandle(
        "initstate",
        constants$5.initstate$FUNC, false
    );
    static final FunctionDescriptor setstate$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle setstate$MH = RuntimeHelper.downcallHandle(
        "setstate",
        constants$5.setstate$FUNC, false
    );
    static final FunctionDescriptor random_r$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle random_r$MH = RuntimeHelper.downcallHandle(
        "random_r",
        constants$5.random_r$FUNC, false
    );
    static final FunctionDescriptor srandom_r$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle srandom_r$MH = RuntimeHelper.downcallHandle(
        "srandom_r",
        constants$5.srandom_r$FUNC, false
    );
    static final FunctionDescriptor initstate_r$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle initstate_r$MH = RuntimeHelper.downcallHandle(
        "initstate_r",
        constants$5.initstate_r$FUNC, false
    );
}


