// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1022 {

    static final FunctionDescriptor a2i_IPADDRESS_NC$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle a2i_IPADDRESS_NC$MH = RuntimeHelper.downcallHandle(
        "a2i_IPADDRESS_NC",
        constants$1022.a2i_IPADDRESS_NC$FUNC, false
    );
    static final FunctionDescriptor X509V3_NAME_from_section$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle X509V3_NAME_from_section$MH = RuntimeHelper.downcallHandle(
        "X509V3_NAME_from_section",
        constants$1022.X509V3_NAME_from_section$FUNC, false
    );
    static final FunctionDescriptor X509_POLICY_NODE_print$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_POLICY_NODE_print$MH = RuntimeHelper.downcallHandle(
        "X509_POLICY_NODE_print",
        constants$1022.X509_POLICY_NODE_print$FUNC, false
    );
    static final FunctionDescriptor sk_X509_POLICY_NODE_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_POLICY_NODE_compfunc$MH = RuntimeHelper.downcallHandle(
        constants$1022.sk_X509_POLICY_NODE_compfunc$FUNC, false
    );
    static final FunctionDescriptor sk_X509_POLICY_NODE_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
}


