// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1115 {

    static final FunctionDescriptor ENGINE_set_default$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_set_default$MH = RuntimeHelper.downcallHandle(
        "ENGINE_set_default",
        constants$1115.ENGINE_set_default$FUNC, false
    );
    static final FunctionDescriptor ENGINE_add_conf_module$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ENGINE_add_conf_module$MH = RuntimeHelper.downcallHandle(
        "ENGINE_add_conf_module",
        constants$1115.ENGINE_add_conf_module$FUNC, false
    );
    static final FunctionDescriptor dyn_MEM_malloc_fn$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_LONG,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle dyn_MEM_malloc_fn$MH = RuntimeHelper.downcallHandle(
        constants$1115.dyn_MEM_malloc_fn$FUNC, false
    );
    static final FunctionDescriptor dyn_MEM_realloc_fn$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_LONG,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle dyn_MEM_realloc_fn$MH = RuntimeHelper.downcallHandle(
        constants$1115.dyn_MEM_realloc_fn$FUNC, false
    );
}


