// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1108 {

    static final FunctionDescriptor ENGINE_get_init_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_init_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_init_function",
        constants$1108.ENGINE_get_init_function$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_finish_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_finish_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_finish_function",
        constants$1108.ENGINE_get_finish_function$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_ctrl_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_ctrl_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_ctrl_function",
        constants$1108.ENGINE_get_ctrl_function$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_load_privkey_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_load_privkey_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_load_privkey_function",
        constants$1108.ENGINE_get_load_privkey_function$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_load_pubkey_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_load_pubkey_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_load_pubkey_function",
        constants$1108.ENGINE_get_load_pubkey_function$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_ssl_client_cert_function$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_ssl_client_cert_function$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_ssl_client_cert_function",
        constants$1108.ENGINE_get_ssl_client_cert_function$FUNC, false
    );
}


