// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$549 {

    static final FunctionDescriptor sk_X509_VERIFY_PARAM_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_reserve",
        constants$549.sk_X509_VERIFY_PARAM_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_X509_VERIFY_PARAM_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_free$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_free",
        constants$549.sk_X509_VERIFY_PARAM_free$FUNC, false
    );
    static final FunctionDescriptor sk_X509_VERIFY_PARAM_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_zero$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_zero",
        constants$549.sk_X509_VERIFY_PARAM_zero$FUNC, false
    );
    static final FunctionDescriptor sk_X509_VERIFY_PARAM_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_delete$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_delete",
        constants$549.sk_X509_VERIFY_PARAM_delete$FUNC, false
    );
    static final FunctionDescriptor sk_X509_VERIFY_PARAM_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_delete_ptr",
        constants$549.sk_X509_VERIFY_PARAM_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_X509_VERIFY_PARAM_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_VERIFY_PARAM_push$MH = RuntimeHelper.downcallHandle(
        "sk_X509_VERIFY_PARAM_push",
        constants$549.sk_X509_VERIFY_PARAM_push$FUNC, false
    );
}


