// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$488 {

    static final FunctionDescriptor sk_X509_NAME_new_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle sk_X509_NAME_new_null$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_new_null",
        constants$488.sk_X509_NAME_new_null$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_new_reserve$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_NAME_new_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_new_reserve",
        constants$488.sk_X509_NAME_new_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_NAME_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_reserve",
        constants$488.sk_X509_NAME_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_NAME_free$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_free",
        constants$488.sk_X509_NAME_free$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_X509_NAME_zero$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_zero",
        constants$488.sk_X509_NAME_zero$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_X509_NAME_delete$MH = RuntimeHelper.downcallHandle(
        "sk_X509_NAME_delete",
        constants$488.sk_X509_NAME_delete$FUNC, false
    );
}


