// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1061 {

    static final FunctionDescriptor sk_ADMISSIONS_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ADMISSIONS_delete$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_delete",
        constants$1061.sk_ADMISSIONS_delete$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_delete_ptr",
        constants$1061.sk_ADMISSIONS_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_push$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_push",
        constants$1061.sk_ADMISSIONS_push$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_unshift$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_unshift$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_unshift",
        constants$1061.sk_ADMISSIONS_unshift$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_pop$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_pop$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_pop",
        constants$1061.sk_ADMISSIONS_pop$FUNC, false
    );
    static final FunctionDescriptor sk_ADMISSIONS_shift$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ADMISSIONS_shift$MH = RuntimeHelper.downcallHandle(
        "sk_ADMISSIONS_shift",
        constants$1061.sk_ADMISSIONS_shift$FUNC, false
    );
}


