// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1150 {

    static final MemorySegment SN_ISO_CN$SEGMENT = ResourceScope.globalScope().allocateUtf8String("ISO-CN");
    static final MemorySegment LN_ISO_CN$SEGMENT = ResourceScope.globalScope().allocateUtf8String("ISO CN Member Body");
    static final MemorySegment SN_oscca$SEGMENT = ResourceScope.globalScope().allocateUtf8String("oscca");
    static final MemorySegment SN_sm_scheme$SEGMENT = ResourceScope.globalScope().allocateUtf8String("sm-scheme");
    static final MemorySegment SN_dsa$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DSA");
    static final MemorySegment LN_dsa$SEGMENT = ResourceScope.globalScope().allocateUtf8String("dsaEncryption");
}


