// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1249 {

    static final MemorySegment LN_des_ede_ofb64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("des-ede-ofb");
    static final MemorySegment SN_des_ede3_ofb64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DES-EDE3-OFB");
    static final MemorySegment LN_des_ede3_ofb64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("des-ede3-ofb");
    static final MemorySegment SN_desx_cbc$SEGMENT = ResourceScope.globalScope().allocateUtf8String("DESX-CBC");
    static final MemorySegment LN_desx_cbc$SEGMENT = ResourceScope.globalScope().allocateUtf8String("desx-cbc");
    static final MemorySegment SN_sha$SEGMENT = ResourceScope.globalScope().allocateUtf8String("SHA");
}


