// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$725 {

    static final FunctionDescriptor PEM_write_DHxparams$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_write_DHxparams$MH = RuntimeHelper.downcallHandle(
        "PEM_write_DHxparams",
        constants$725.PEM_write_DHxparams$FUNC, false
    );
    static final FunctionDescriptor PEM_read_bio_PrivateKey$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_read_bio_PrivateKey$MH = RuntimeHelper.downcallHandle(
        "PEM_read_bio_PrivateKey",
        constants$725.PEM_read_bio_PrivateKey$FUNC, false
    );
    static final FunctionDescriptor PEM_read_PrivateKey$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_read_PrivateKey$MH = RuntimeHelper.downcallHandle(
        "PEM_read_PrivateKey",
        constants$725.PEM_read_PrivateKey$FUNC, false
    );
    static final FunctionDescriptor PEM_write_bio_PrivateKey$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_write_bio_PrivateKey$MH = RuntimeHelper.downcallHandle(
        "PEM_write_bio_PrivateKey",
        constants$725.PEM_write_bio_PrivateKey$FUNC, false
    );
    static final FunctionDescriptor PEM_write_PrivateKey$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_write_PrivateKey$MH = RuntimeHelper.downcallHandle(
        "PEM_write_PrivateKey",
        constants$725.PEM_write_PrivateKey$FUNC, false
    );
    static final FunctionDescriptor PEM_read_bio_PUBKEY$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_read_bio_PUBKEY$MH = RuntimeHelper.downcallHandle(
        "PEM_read_bio_PUBKEY",
        constants$725.PEM_read_bio_PUBKEY$FUNC, false
    );
}


