// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1127 {

    static final MemorySegment PRIxLEAST16$SEGMENT = ResourceScope.globalScope().allocateUtf8String("x");
    static final MemorySegment PRIxLEAST32$SEGMENT = ResourceScope.globalScope().allocateUtf8String("x");
    static final MemorySegment PRIxLEAST64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("lx");
    static final MemorySegment PRIxFAST8$SEGMENT = ResourceScope.globalScope().allocateUtf8String("x");
    static final MemorySegment PRIxFAST16$SEGMENT = ResourceScope.globalScope().allocateUtf8String("lx");
    static final MemorySegment PRIxFAST32$SEGMENT = ResourceScope.globalScope().allocateUtf8String("lx");
}


