// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1048 {

    static final FunctionDescriptor X509v3_asid_add_id_or_range$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509v3_asid_add_id_or_range$MH = RuntimeHelper.downcallHandle(
        "X509v3_asid_add_id_or_range",
        constants$1048.X509v3_asid_add_id_or_range$FUNC, false
    );
    static final FunctionDescriptor X509v3_addr_add_inherit$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509v3_addr_add_inherit$MH = RuntimeHelper.downcallHandle(
        "X509v3_addr_add_inherit",
        constants$1048.X509v3_addr_add_inherit$FUNC, false
    );
    static final FunctionDescriptor X509v3_addr_add_prefix$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509v3_addr_add_prefix$MH = RuntimeHelper.downcallHandle(
        "X509v3_addr_add_prefix",
        constants$1048.X509v3_addr_add_prefix$FUNC, false
    );
    static final FunctionDescriptor X509v3_addr_add_range$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509v3_addr_add_range$MH = RuntimeHelper.downcallHandle(
        "X509v3_addr_add_range",
        constants$1048.X509v3_addr_add_range$FUNC, false
    );
    static final FunctionDescriptor X509v3_addr_get_afi$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509v3_addr_get_afi$MH = RuntimeHelper.downcallHandle(
        "X509v3_addr_get_afi",
        constants$1048.X509v3_addr_get_afi$FUNC, false
    );
    static final FunctionDescriptor X509v3_addr_get_range$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509v3_addr_get_range$MH = RuntimeHelper.downcallHandle(
        "X509v3_addr_get_range",
        constants$1048.X509v3_addr_get_range$FUNC, false
    );
}


