// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$851 {

    static final FunctionDescriptor SSL_SESSION_get_max_fragment_length$FUNC = FunctionDescriptor.of(JAVA_BYTE,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_get_max_fragment_length$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_get_max_fragment_length",
        constants$851.SSL_SESSION_get_max_fragment_length$FUNC, false
    );
    static final FunctionDescriptor SSL_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle SSL_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "SSL_set_ex_data",
        constants$851.SSL_set_ex_data$FUNC, false
    );
    static final FunctionDescriptor SSL_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle SSL_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "SSL_get_ex_data",
        constants$851.SSL_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_set_ex_data",
        constants$851.SSL_SESSION_set_ex_data$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle SSL_SESSION_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_get_ex_data",
        constants$851.SSL_SESSION_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_set_ex_data",
        constants$851.SSL_CTX_set_ex_data$FUNC, false
    );
}


