// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$186 {

    static final FunctionDescriptor sk_ASN1_INTEGER_value$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_INTEGER_value$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_value",
        constants$186.sk_ASN1_INTEGER_value$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_INTEGER_new$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_INTEGER_new$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_new",
        constants$186.sk_ASN1_INTEGER_new$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_INTEGER_new_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle sk_ASN1_INTEGER_new_null$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_new_null",
        constants$186.sk_ASN1_INTEGER_new_null$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_INTEGER_new_reserve$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_INTEGER_new_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_new_reserve",
        constants$186.sk_ASN1_INTEGER_new_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_INTEGER_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_INTEGER_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_reserve",
        constants$186.sk_ASN1_INTEGER_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_INTEGER_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ASN1_INTEGER_free$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_INTEGER_free",
        constants$186.sk_ASN1_INTEGER_free$FUNC, false
    );
}


