// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1231 {

    static final MemorySegment SN_id_alg_des40$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-alg-des40");
    static final MemorySegment SN_id_alg_noSignature$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-alg-noSignature");
    static final MemorySegment SN_id_alg_dh_sig_hmac_sha1$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-alg-dh-sig-hmac-sha1");
    static final MemorySegment SN_id_alg_dh_pop$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-alg-dh-pop");
    static final MemorySegment SN_id_cmc_statusInfo$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-cmc-statusInfo");
    static final MemorySegment SN_id_cmc_identification$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-cmc-identification");
}


