// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$253 {

    static final FunctionDescriptor ERR_load_OBJ_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_OBJ_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_OBJ_strings",
        constants$253.ERR_load_OBJ_strings$FUNC, false
    );
    static final FunctionDescriptor OBJ_NAME_init$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle OBJ_NAME_init$MH = RuntimeHelper.downcallHandle(
        "OBJ_NAME_init",
        constants$253.OBJ_NAME_init$FUNC, false
    );
    static final FunctionDescriptor OBJ_NAME_new_index$hash_func$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle OBJ_NAME_new_index$hash_func$MH = RuntimeHelper.downcallHandle(
        constants$253.OBJ_NAME_new_index$hash_func$FUNC, false
    );
    static final FunctionDescriptor OBJ_NAME_new_index$cmp_func$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle OBJ_NAME_new_index$cmp_func$MH = RuntimeHelper.downcallHandle(
        constants$253.OBJ_NAME_new_index$cmp_func$FUNC, false
    );
}


