// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1122 {

    static final MemorySegment PRIiFAST64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("li");
    static final MemorySegment PRIo8$SEGMENT = ResourceScope.globalScope().allocateUtf8String("o");
    static final MemorySegment PRIo16$SEGMENT = ResourceScope.globalScope().allocateUtf8String("o");
    static final MemorySegment PRIo32$SEGMENT = ResourceScope.globalScope().allocateUtf8String("o");
    static final MemorySegment PRIo64$SEGMENT = ResourceScope.globalScope().allocateUtf8String("lo");
    static final MemorySegment PRIoLEAST8$SEGMENT = ResourceScope.globalScope().allocateUtf8String("o");
}


