// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$438 {

    static final FunctionDescriptor RSA_meth_get_pub_enc$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle RSA_meth_get_pub_enc$MH = RuntimeHelper.downcallHandle(
        "RSA_meth_get_pub_enc",
        constants$438.RSA_meth_get_pub_enc$FUNC, false
    );
    static final FunctionDescriptor RSA_meth_set_pub_enc$pub_enc$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle RSA_meth_set_pub_enc$pub_enc$MH = RuntimeHelper.downcallHandle(
        constants$438.RSA_meth_set_pub_enc$pub_enc$FUNC, false
    );
    static final FunctionDescriptor RSA_meth_set_pub_enc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle RSA_meth_set_pub_enc$MH = RuntimeHelper.downcallHandle(
        "RSA_meth_set_pub_enc",
        constants$438.RSA_meth_set_pub_enc$FUNC, false
    );
    static final FunctionDescriptor RSA_meth_get_pub_dec$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle RSA_meth_get_pub_dec$MH = RuntimeHelper.downcallHandle(
        "RSA_meth_get_pub_dec",
        constants$438.RSA_meth_get_pub_dec$FUNC, false
    );
    static final FunctionDescriptor RSA_meth_set_pub_dec$pub_dec$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
}


