// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$790 {

    static final FunctionDescriptor sk_SSL_COMP_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_SSL_COMP_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_reserve",
        constants$790.sk_SSL_COMP_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_free$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_free",
        constants$790.sk_SSL_COMP_free$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_zero$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_zero",
        constants$790.sk_SSL_COMP_zero$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_SSL_COMP_delete$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_delete",
        constants$790.sk_SSL_COMP_delete$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_delete_ptr",
        constants$790.sk_SSL_COMP_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_push$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_push",
        constants$790.sk_SSL_COMP_push$FUNC, false
    );
}


