// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$165 {

    static final FunctionDescriptor BN_X931_derive_prime_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_X931_derive_prime_ex$MH = RuntimeHelper.downcallHandle(
        "BN_X931_derive_prime_ex",
        constants$165.BN_X931_derive_prime_ex$FUNC, false
    );
    static final FunctionDescriptor BN_X931_generate_prime_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_X931_generate_prime_ex$MH = RuntimeHelper.downcallHandle(
        "BN_X931_generate_prime_ex",
        constants$165.BN_X931_generate_prime_ex$FUNC, false
    );
    static final FunctionDescriptor BN_MONT_CTX_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BN_MONT_CTX_new$MH = RuntimeHelper.downcallHandle(
        "BN_MONT_CTX_new",
        constants$165.BN_MONT_CTX_new$FUNC, false
    );
    static final FunctionDescriptor BN_mod_mul_montgomery$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_mod_mul_montgomery$MH = RuntimeHelper.downcallHandle(
        "BN_mod_mul_montgomery",
        constants$165.BN_mod_mul_montgomery$FUNC, false
    );
    static final FunctionDescriptor BN_to_montgomery$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_to_montgomery$MH = RuntimeHelper.downcallHandle(
        "BN_to_montgomery",
        constants$165.BN_to_montgomery$FUNC, false
    );
    static final FunctionDescriptor BN_from_montgomery$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_from_montgomery$MH = RuntimeHelper.downcallHandle(
        "BN_from_montgomery",
        constants$165.BN_from_montgomery$FUNC, false
    );
}


