// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$459 {

    static final FunctionDescriptor DH_meth_set_init$init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DH_meth_set_init$init$MH = RuntimeHelper.downcallHandle(
        constants$459.DH_meth_set_init$init$FUNC, false
    );
    static final FunctionDescriptor DH_meth_set_init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle DH_meth_set_init$MH = RuntimeHelper.downcallHandle(
        "DH_meth_set_init",
        constants$459.DH_meth_set_init$FUNC, false
    );
    static final FunctionDescriptor DH_meth_get_finish$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle DH_meth_get_finish$MH = RuntimeHelper.downcallHandle(
        "DH_meth_get_finish",
        constants$459.DH_meth_get_finish$FUNC, false
    );
    static final FunctionDescriptor DH_meth_set_finish$finish$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DH_meth_set_finish$finish$MH = RuntimeHelper.downcallHandle(
        constants$459.DH_meth_set_finish$finish$FUNC, false
    );
    static final FunctionDescriptor DH_meth_set_finish$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle DH_meth_set_finish$MH = RuntimeHelper.downcallHandle(
        "DH_meth_set_finish",
        constants$459.DH_meth_set_finish$FUNC, false
    );
}


