// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1409 {

    static final MemorySegment LN_jurisdictionCountryName$SEGMENT = ResourceScope.globalScope().allocateUtf8String("jurisdictionCountryName");
    static final MemorySegment SN_id_scrypt$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-scrypt");
    static final MemorySegment LN_id_scrypt$SEGMENT = ResourceScope.globalScope().allocateUtf8String("scrypt");
    static final MemorySegment SN_tls1_prf$SEGMENT = ResourceScope.globalScope().allocateUtf8String("TLS1-PRF");
    static final MemorySegment LN_tls1_prf$SEGMENT = ResourceScope.globalScope().allocateUtf8String("tls1-prf");
    static final MemorySegment SN_hkdf$SEGMENT = ResourceScope.globalScope().allocateUtf8String("HKDF");
}


