// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1092 {

    static final FunctionDescriptor ENGINE_GEN_INT_FUNC_PTR$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_GEN_INT_FUNC_PTR$MH = RuntimeHelper.downcallHandle(
        constants$1092.ENGINE_GEN_INT_FUNC_PTR$FUNC, false
    );
    static final FunctionDescriptor ENGINE_CTRL_FUNC_PTR$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_LONG,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_CTRL_FUNC_PTR$MH = RuntimeHelper.downcallHandle(
        constants$1092.ENGINE_CTRL_FUNC_PTR$FUNC, false
    );
    static final FunctionDescriptor ENGINE_LOAD_KEY_PTR$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_LOAD_KEY_PTR$MH = RuntimeHelper.downcallHandle(
        constants$1092.ENGINE_LOAD_KEY_PTR$FUNC, false
    );
}


