// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$639 {

    static final FunctionDescriptor d2i_PrivateKey_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_PrivateKey_bio",
        constants$639.d2i_PrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_PUBKEY_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PUBKEY_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_PUBKEY_bio",
        constants$639.i2d_PUBKEY_bio$FUNC, false
    );
    static final FunctionDescriptor d2i_PUBKEY_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PUBKEY_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_PUBKEY_bio",
        constants$639.d2i_PUBKEY_bio$FUNC, false
    );
    static final FunctionDescriptor X509_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_dup$MH = RuntimeHelper.downcallHandle(
        "X509_dup",
        constants$639.X509_dup$FUNC, false
    );
    static final FunctionDescriptor X509_ATTRIBUTE_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_ATTRIBUTE_dup$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_dup",
        constants$639.X509_ATTRIBUTE_dup$FUNC, false
    );
    static final FunctionDescriptor X509_EXTENSION_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_EXTENSION_dup$MH = RuntimeHelper.downcallHandle(
        "X509_EXTENSION_dup",
        constants$639.X509_EXTENSION_dup$FUNC, false
    );
}


