// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1112 {

    static final FunctionDescriptor ENGINE_get_default_DSA$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ENGINE_get_default_DSA$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_default_DSA",
        constants$1112.ENGINE_get_default_DSA$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_default_EC$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ENGINE_get_default_EC$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_default_EC",
        constants$1112.ENGINE_get_default_EC$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_default_DH$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ENGINE_get_default_DH$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_default_DH",
        constants$1112.ENGINE_get_default_DH$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_default_RAND$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ENGINE_get_default_RAND$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_default_RAND",
        constants$1112.ENGINE_get_default_RAND$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_cipher_engine$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_cipher_engine$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_cipher_engine",
        constants$1112.ENGINE_get_cipher_engine$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_digest_engine$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_digest_engine$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_digest_engine",
        constants$1112.ENGINE_get_digest_engine$FUNC, false
    );
}


