// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1518 {

    static final MemorySegment TLS1_TXT_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDHE-RSA-CAMELLIA128-SHA256");
    static final MemorySegment TLS1_TXT_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDHE-RSA-CAMELLIA256-SHA384");
    static final MemorySegment TLS1_TXT_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDH-RSA-CAMELLIA128-SHA256");
    static final MemorySegment TLS1_TXT_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDH-RSA-CAMELLIA256-SHA384");
    static final MemorySegment TLS1_TXT_ECDHE_RSA_WITH_CHACHA20_POLY1305$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDHE-RSA-CHACHA20-POLY1305");
    static final MemorySegment TLS1_TXT_ECDHE_ECDSA_WITH_CHACHA20_POLY1305$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ECDHE-ECDSA-CHACHA20-POLY1305");
}


