// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$968 {

    static final FunctionDescriptor sk_POLICYINFO_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_POLICYINFO_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_reserve",
        constants$968.sk_POLICYINFO_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_POLICYINFO_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_POLICYINFO_free$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_free",
        constants$968.sk_POLICYINFO_free$FUNC, false
    );
    static final FunctionDescriptor sk_POLICYINFO_zero$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_POLICYINFO_zero$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_zero",
        constants$968.sk_POLICYINFO_zero$FUNC, false
    );
    static final FunctionDescriptor sk_POLICYINFO_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_POLICYINFO_delete$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_delete",
        constants$968.sk_POLICYINFO_delete$FUNC, false
    );
    static final FunctionDescriptor sk_POLICYINFO_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_POLICYINFO_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_delete_ptr",
        constants$968.sk_POLICYINFO_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_POLICYINFO_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_POLICYINFO_push$MH = RuntimeHelper.downcallHandle(
        "sk_POLICYINFO_push",
        constants$968.sk_POLICYINFO_push$FUNC, false
    );
}


