// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1350 {

    static final MemorySegment LN_id_GostR3411_94_with_GostR3410_94$SEGMENT = ResourceScope.globalScope().allocateUtf8String("GOST R 34.11-94 with GOST R 34.10-94");
    static final MemorySegment SN_id_GostR3411_94$SEGMENT = ResourceScope.globalScope().allocateUtf8String("md_gost94");
    static final MemorySegment LN_id_GostR3411_94$SEGMENT = ResourceScope.globalScope().allocateUtf8String("GOST R 34.11-94");
    static final MemorySegment SN_id_HMACGostR3411_94$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-HMACGostR3411-94");
    static final MemorySegment LN_id_HMACGostR3411_94$SEGMENT = ResourceScope.globalScope().allocateUtf8String("HMAC GOST 34.11-94");
    static final MemorySegment SN_id_GostR3410_2001$SEGMENT = ResourceScope.globalScope().allocateUtf8String("gost2001");
}


