// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$690 {

    static final FunctionDescriptor X509_get_ext_by_NID$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle X509_get_ext_by_NID$MH = RuntimeHelper.downcallHandle(
        "X509_get_ext_by_NID",
        constants$690.X509_get_ext_by_NID$FUNC, false
    );
    static final FunctionDescriptor X509_get_ext_by_OBJ$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_get_ext_by_OBJ$MH = RuntimeHelper.downcallHandle(
        "X509_get_ext_by_OBJ",
        constants$690.X509_get_ext_by_OBJ$FUNC, false
    );
    static final FunctionDescriptor X509_get_ext_by_critical$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle X509_get_ext_by_critical$MH = RuntimeHelper.downcallHandle(
        "X509_get_ext_by_critical",
        constants$690.X509_get_ext_by_critical$FUNC, false
    );
    static final FunctionDescriptor X509_get_ext$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_get_ext$MH = RuntimeHelper.downcallHandle(
        "X509_get_ext",
        constants$690.X509_get_ext$FUNC, false
    );
    static final FunctionDescriptor X509_delete_ext$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_delete_ext$MH = RuntimeHelper.downcallHandle(
        "X509_delete_ext",
        constants$690.X509_delete_ext$FUNC, false
    );
    static final FunctionDescriptor X509_add_ext$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_add_ext$MH = RuntimeHelper.downcallHandle(
        "X509_add_ext",
        constants$690.X509_add_ext$FUNC, false
    );
}


