// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1235 {

    static final MemorySegment SN_id_on_personalData$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-on-personalData");
    static final MemorySegment SN_id_on_permanentIdentifier$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-on-permanentIdentifier");
    static final MemorySegment LN_id_on_permanentIdentifier$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Permanent Identifier");
    static final MemorySegment SN_id_pda_dateOfBirth$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-pda-dateOfBirth");
    static final MemorySegment SN_id_pda_placeOfBirth$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-pda-placeOfBirth");
    static final MemorySegment SN_id_pda_gender$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-pda-gender");
}


