// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$221 {

    static final FunctionDescriptor i2d_ASN1_OCTET_STRING$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_ASN1_OCTET_STRING$MH = RuntimeHelper.downcallHandle(
        "i2d_ASN1_OCTET_STRING",
        constants$221.i2d_ASN1_OCTET_STRING$FUNC, false
    );
    static final FunctionDescriptor ASN1_OCTET_STRING_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_OCTET_STRING_dup$MH = RuntimeHelper.downcallHandle(
        "ASN1_OCTET_STRING_dup",
        constants$221.ASN1_OCTET_STRING_dup$FUNC, false
    );
    static final FunctionDescriptor ASN1_OCTET_STRING_cmp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_OCTET_STRING_cmp$MH = RuntimeHelper.downcallHandle(
        "ASN1_OCTET_STRING_cmp",
        constants$221.ASN1_OCTET_STRING_cmp$FUNC, false
    );
    static final FunctionDescriptor ASN1_OCTET_STRING_set$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ASN1_OCTET_STRING_set$MH = RuntimeHelper.downcallHandle(
        "ASN1_OCTET_STRING_set",
        constants$221.ASN1_OCTET_STRING_set$FUNC, false
    );
    static final FunctionDescriptor ASN1_VISIBLESTRING_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ASN1_VISIBLESTRING_new$MH = RuntimeHelper.downcallHandle(
        "ASN1_VISIBLESTRING_new",
        constants$221.ASN1_VISIBLESTRING_new$FUNC, false
    );
    static final FunctionDescriptor ASN1_VISIBLESTRING_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ASN1_VISIBLESTRING_free$MH = RuntimeHelper.downcallHandle(
        "ASN1_VISIBLESTRING_free",
        constants$221.ASN1_VISIBLESTRING_free$FUNC, false
    );
}


