// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$123 {

    static final FunctionDescriptor BIO_s_log$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_s_log$MH = RuntimeHelper.downcallHandle(
        "BIO_s_log",
        constants$123.BIO_s_log$FUNC, false
    );
    static final FunctionDescriptor BIO_s_bio$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_s_bio$MH = RuntimeHelper.downcallHandle(
        "BIO_s_bio",
        constants$123.BIO_s_bio$FUNC, false
    );
    static final FunctionDescriptor BIO_s_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_s_null$MH = RuntimeHelper.downcallHandle(
        "BIO_s_null",
        constants$123.BIO_s_null$FUNC, false
    );
    static final FunctionDescriptor BIO_f_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_f_null$MH = RuntimeHelper.downcallHandle(
        "BIO_f_null",
        constants$123.BIO_f_null$FUNC, false
    );
    static final FunctionDescriptor BIO_f_buffer$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_f_buffer$MH = RuntimeHelper.downcallHandle(
        "BIO_f_buffer",
        constants$123.BIO_f_buffer$FUNC, false
    );
    static final FunctionDescriptor BIO_f_linebuffer$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BIO_f_linebuffer$MH = RuntimeHelper.downcallHandle(
        "BIO_f_linebuffer",
        constants$123.BIO_f_linebuffer$FUNC, false
    );
}


