// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$194 {

    static final FunctionDescriptor sk_ASN1_GENERALSTRING_sort$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ASN1_GENERALSTRING_sort$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_GENERALSTRING_sort",
        constants$194.sk_ASN1_GENERALSTRING_sort$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_GENERALSTRING_is_sorted$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_GENERALSTRING_is_sorted$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_GENERALSTRING_is_sorted",
        constants$194.sk_ASN1_GENERALSTRING_is_sorted$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_GENERALSTRING_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_GENERALSTRING_dup$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_GENERALSTRING_dup",
        constants$194.sk_ASN1_GENERALSTRING_dup$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_GENERALSTRING_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_GENERALSTRING_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_GENERALSTRING_deep_copy",
        constants$194.sk_ASN1_GENERALSTRING_deep_copy$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_GENERALSTRING_set_cmp_func$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_GENERALSTRING_set_cmp_func$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_GENERALSTRING_set_cmp_func",
        constants$194.sk_ASN1_GENERALSTRING_set_cmp_func$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
}


