// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$792 {

    static final FunctionDescriptor sk_SSL_COMP_find$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_find$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_find",
        constants$792.sk_SSL_COMP_find$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_find_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_find_ex$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_find_ex",
        constants$792.sk_SSL_COMP_find_ex$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_sort$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_sort$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_sort",
        constants$792.sk_SSL_COMP_sort$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_is_sorted$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_is_sorted$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_is_sorted",
        constants$792.sk_SSL_COMP_is_sorted$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_dup$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_dup",
        constants$792.sk_SSL_COMP_dup$FUNC, false
    );
    static final FunctionDescriptor sk_SSL_COMP_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SSL_COMP_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_SSL_COMP_deep_copy",
        constants$792.sk_SSL_COMP_deep_copy$FUNC, false
    );
}


