// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$691 {

    static final FunctionDescriptor X509_get_ext_d2i$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_get_ext_d2i$MH = RuntimeHelper.downcallHandle(
        "X509_get_ext_d2i",
        constants$691.X509_get_ext_d2i$FUNC, false
    );
    static final FunctionDescriptor X509_add1_ext_i2d$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle X509_add1_ext_i2d$MH = RuntimeHelper.downcallHandle(
        "X509_add1_ext_i2d",
        constants$691.X509_add1_ext_i2d$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_get_ext_count$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_CRL_get_ext_count$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_get_ext_count",
        constants$691.X509_CRL_get_ext_count$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_get_ext_by_NID$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle X509_CRL_get_ext_by_NID$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_get_ext_by_NID",
        constants$691.X509_CRL_get_ext_by_NID$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_get_ext_by_OBJ$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_CRL_get_ext_by_OBJ$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_get_ext_by_OBJ",
        constants$691.X509_CRL_get_ext_by_OBJ$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_get_ext_by_critical$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle X509_CRL_get_ext_by_critical$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_get_ext_by_critical",
        constants$691.X509_CRL_get_ext_by_critical$FUNC, false
    );
}


