// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$372 {

    static final FunctionDescriptor EVP_PKEY_meth_get_sign$psign_init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_sign$psign_init$MH = RuntimeHelper.downcallHandle(
        constants$372.EVP_PKEY_meth_get_sign$psign_init$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_sign$psign$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle EVP_PKEY_meth_get_sign$psign$MH = RuntimeHelper.downcallHandle(
        constants$372.EVP_PKEY_meth_get_sign$psign$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_sign$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_sign$MH = RuntimeHelper.downcallHandle(
        "EVP_PKEY_meth_get_sign",
        constants$372.EVP_PKEY_meth_get_sign$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_verify$pverify_init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
}


