// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$753 {

    static final FunctionDescriptor o2i_SCT$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle o2i_SCT$MH = RuntimeHelper.downcallHandle(
        "o2i_SCT",
        constants$753.o2i_SCT$FUNC, false
    );
    static final FunctionDescriptor CTLOG_new$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle CTLOG_new$MH = RuntimeHelper.downcallHandle(
        "CTLOG_new",
        constants$753.CTLOG_new$FUNC, false
    );
    static final FunctionDescriptor CTLOG_new_from_base64$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle CTLOG_new_from_base64$MH = RuntimeHelper.downcallHandle(
        "CTLOG_new_from_base64",
        constants$753.CTLOG_new_from_base64$FUNC, false
    );
    static final FunctionDescriptor CTLOG_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle CTLOG_free$MH = RuntimeHelper.downcallHandle(
        "CTLOG_free",
        constants$753.CTLOG_free$FUNC, false
    );
    static final FunctionDescriptor CTLOG_get0_name$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle CTLOG_get0_name$MH = RuntimeHelper.downcallHandle(
        "CTLOG_get0_name",
        constants$753.CTLOG_get0_name$FUNC, false
    );
    static final FunctionDescriptor CTLOG_get0_log_id$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle CTLOG_get0_log_id$MH = RuntimeHelper.downcallHandle(
        "CTLOG_get0_log_id",
        constants$753.CTLOG_get0_log_id$FUNC, false
    );
}


