// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1353 {

    static final MemorySegment SN_gost_mac_12$SEGMENT = ResourceScope.globalScope().allocateUtf8String("gost-mac-12");
    static final MemorySegment SN_id_GostR3411_94_prf$SEGMENT = ResourceScope.globalScope().allocateUtf8String("prf-gostr3411-94");
    static final MemorySegment LN_id_GostR3411_94_prf$SEGMENT = ResourceScope.globalScope().allocateUtf8String("GOST R 34.11-94 PRF");
    static final MemorySegment SN_id_GostR3410_2001DH$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-GostR3410-2001DH");
    static final MemorySegment LN_id_GostR3410_2001DH$SEGMENT = ResourceScope.globalScope().allocateUtf8String("GOST R 34.10-2001 DH");
    static final MemorySegment SN_id_GostR3410_94DH$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-GostR3410-94DH");
}


