// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1312 {

    static final MemorySegment LN_iA5StringSyntax$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("iA5StringSyntax");
    static final MemorySegment LN_caseIgnoreIA5StringSyntax$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("caseIgnoreIA5StringSyntax");
    static final MemorySegment LN_pilotObject$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pilotObject");
    static final MemorySegment LN_pilotPerson$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pilotPerson");
    static final MemorySegment SN_account$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("account");
    static final MemorySegment SN_document$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("document");
}


