// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$524 {

    static final FunctionDescriptor sk_X509_INFO_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_delete_ptr",
        constants$524.sk_X509_INFO_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_X509_INFO_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_push$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_push",
        constants$524.sk_X509_INFO_push$FUNC, false
    );
    static final FunctionDescriptor sk_X509_INFO_unshift$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_unshift$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_unshift",
        constants$524.sk_X509_INFO_unshift$FUNC, false
    );
    static final FunctionDescriptor sk_X509_INFO_pop$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_pop$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_pop",
        constants$524.sk_X509_INFO_pop$FUNC, false
    );
    static final FunctionDescriptor sk_X509_INFO_shift$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_shift$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_shift",
        constants$524.sk_X509_INFO_shift$FUNC, false
    );
    static final FunctionDescriptor sk_X509_INFO_pop_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_INFO_pop_free$MH = RuntimeHelper.downcallHandle(
        "sk_X509_INFO_pop_free",
        constants$524.sk_X509_INFO_pop_free$FUNC, false
    );
}


