// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$196 {

    static final FunctionDescriptor sk_ASN1_UTF8STRING_value$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_UTF8STRING_value$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_value",
        constants$196.sk_ASN1_UTF8STRING_value$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_new$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_UTF8STRING_new$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_new",
        constants$196.sk_ASN1_UTF8STRING_new$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_new_null$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle sk_ASN1_UTF8STRING_new_null$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_new_null",
        constants$196.sk_ASN1_UTF8STRING_new_null$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_new_reserve$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_UTF8STRING_new_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_new_reserve",
        constants$196.sk_ASN1_UTF8STRING_new_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_reserve$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_ASN1_UTF8STRING_reserve$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_reserve",
        constants$196.sk_ASN1_UTF8STRING_reserve$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_UTF8STRING_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ASN1_UTF8STRING_free$MH = RuntimeHelper.downcallHandle(
        "sk_ASN1_UTF8STRING_free",
        constants$196.sk_ASN1_UTF8STRING_free$FUNC, false
    );
}


