// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$813 {

    static final FunctionDescriptor SSL_SESSION_get0_id_context$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_get0_id_context$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_get0_id_context",
        constants$813.SSL_SESSION_get0_id_context$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_get_compress_id$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_get_compress_id$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_get_compress_id",
        constants$813.SSL_SESSION_get_compress_id$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_print_fp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_print_fp$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_print_fp",
        constants$813.SSL_SESSION_print_fp$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_print$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_print$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_print",
        constants$813.SSL_SESSION_print$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_print_keylog$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_print_keylog$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_print_keylog",
        constants$813.SSL_SESSION_print_keylog$FUNC, false
    );
    static final FunctionDescriptor SSL_SESSION_up_ref$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_up_ref$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_up_ref",
        constants$813.SSL_SESSION_up_ref$FUNC, false
    );
}


