// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1451 {

    static final MemorySegment SSL3_TXT_DH_RSA_DES_64_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("DH-RSA-DES-CBC-SHA");
    static final MemorySegment SSL3_TXT_DH_RSA_DES_192_CBC3_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("DH-RSA-DES-CBC3-SHA");
    static final MemorySegment SSL3_TXT_DHE_DSS_DES_40_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("EXP-DHE-DSS-DES-CBC-SHA");
    static final MemorySegment SSL3_TXT_DHE_DSS_DES_64_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("DHE-DSS-DES-CBC-SHA");
    static final MemorySegment SSL3_TXT_DHE_DSS_DES_192_CBC3_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("DHE-DSS-DES-CBC3-SHA");
    static final MemorySegment SSL3_TXT_DHE_RSA_DES_40_CBC_SHA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("EXP-DHE-RSA-DES-CBC-SHA");
}


