// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$987 {

    static final FunctionDescriptor sk_X509_PURPOSE_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_PURPOSE_dup$MH = RuntimeHelper.downcallHandle(
        "sk_X509_PURPOSE_dup",
        constants$987.sk_X509_PURPOSE_dup$FUNC, false
    );
    static final FunctionDescriptor sk_X509_PURPOSE_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_PURPOSE_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_X509_PURPOSE_deep_copy",
        constants$987.sk_X509_PURPOSE_deep_copy$FUNC, false
    );
    static final FunctionDescriptor sk_X509_PURPOSE_set_cmp_func$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_PURPOSE_set_cmp_func$MH = RuntimeHelper.downcallHandle(
        "sk_X509_PURPOSE_set_cmp_func",
        constants$987.sk_X509_PURPOSE_set_cmp_func$FUNC, false
    );
    static final FunctionDescriptor BASIC_CONSTRAINTS_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BASIC_CONSTRAINTS_new$MH = RuntimeHelper.downcallHandle(
        "BASIC_CONSTRAINTS_new",
        constants$987.BASIC_CONSTRAINTS_new$FUNC, false
    );
    static final FunctionDescriptor BASIC_CONSTRAINTS_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle BASIC_CONSTRAINTS_free$MH = RuntimeHelper.downcallHandle(
        "BASIC_CONSTRAINTS_free",
        constants$987.BASIC_CONSTRAINTS_free$FUNC, false
    );
    static final FunctionDescriptor d2i_BASIC_CONSTRAINTS$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_BASIC_CONSTRAINTS$MH = RuntimeHelper.downcallHandle(
        "d2i_BASIC_CONSTRAINTS",
        constants$987.d2i_BASIC_CONSTRAINTS$FUNC, false
    );
}


