// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1069 {

    static final FunctionDescriptor NAMING_AUTHORITY_get0_authorityText$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle NAMING_AUTHORITY_get0_authorityText$MH = RuntimeHelper.downcallHandle(
        "NAMING_AUTHORITY_get0_authorityText",
        constants$1069.NAMING_AUTHORITY_get0_authorityText$FUNC, false
    );
    static final FunctionDescriptor NAMING_AUTHORITY_set0_authorityId$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle NAMING_AUTHORITY_set0_authorityId$MH = RuntimeHelper.downcallHandle(
        "NAMING_AUTHORITY_set0_authorityId",
        constants$1069.NAMING_AUTHORITY_set0_authorityId$FUNC, false
    );
    static final FunctionDescriptor NAMING_AUTHORITY_set0_authorityURL$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle NAMING_AUTHORITY_set0_authorityURL$MH = RuntimeHelper.downcallHandle(
        "NAMING_AUTHORITY_set0_authorityURL",
        constants$1069.NAMING_AUTHORITY_set0_authorityURL$FUNC, false
    );
    static final FunctionDescriptor NAMING_AUTHORITY_set0_authorityText$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle NAMING_AUTHORITY_set0_authorityText$MH = RuntimeHelper.downcallHandle(
        "NAMING_AUTHORITY_set0_authorityText",
        constants$1069.NAMING_AUTHORITY_set0_authorityText$FUNC, false
    );
    static final FunctionDescriptor ADMISSION_SYNTAX_get0_admissionAuthority$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ADMISSION_SYNTAX_get0_admissionAuthority$MH = RuntimeHelper.downcallHandle(
        "ADMISSION_SYNTAX_get0_admissionAuthority",
        constants$1069.ADMISSION_SYNTAX_get0_admissionAuthority$FUNC, false
    );
    static final FunctionDescriptor ADMISSION_SYNTAX_set0_admissionAuthority$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ADMISSION_SYNTAX_set0_admissionAuthority$MH = RuntimeHelper.downcallHandle(
        "ADMISSION_SYNTAX_set0_admissionAuthority",
        constants$1069.ADMISSION_SYNTAX_set0_admissionAuthority$FUNC, false
    );
}


