// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1394 {

    static final MemorySegment LN_aria_192_gcm$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aria-192-gcm");
    static final MemorySegment SN_aria_256_gcm$SEGMENT = ResourceScope.globalScope().allocateUtf8String("ARIA-256-GCM");
    static final MemorySegment LN_aria_256_gcm$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aria-256-gcm");
    static final MemorySegment SN_kisa$SEGMENT = ResourceScope.globalScope().allocateUtf8String("KISA");
    static final MemorySegment LN_kisa$SEGMENT = ResourceScope.globalScope().allocateUtf8String("kisa");
    static final MemorySegment SN_seed_ecb$SEGMENT = ResourceScope.globalScope().allocateUtf8String("SEED-ECB");
}


