// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1315 {

    static final MemorySegment SN_userId$SEGMENT = ResourceScope.globalScope().allocateUtf8String("UID");
    static final MemorySegment LN_userId$SEGMENT = ResourceScope.globalScope().allocateUtf8String("userId");
    static final MemorySegment LN_textEncodedORAddress$SEGMENT = ResourceScope.globalScope().allocateUtf8String("textEncodedORAddress");
    static final MemorySegment SN_rfc822Mailbox$SEGMENT = ResourceScope.globalScope().allocateUtf8String("mail");
    static final MemorySegment LN_rfc822Mailbox$SEGMENT = ResourceScope.globalScope().allocateUtf8String("rfc822Mailbox");
    static final MemorySegment SN_info$SEGMENT = ResourceScope.globalScope().allocateUtf8String("info");
}


