// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$129 {

    static final FunctionDescriptor BIO_ADDR_clear$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle BIO_ADDR_clear$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_clear",
        constants$129.BIO_ADDR_clear$FUNC, false
    );
    static final FunctionDescriptor BIO_ADDR_family$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle BIO_ADDR_family$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_family",
        constants$129.BIO_ADDR_family$FUNC, false
    );
    static final FunctionDescriptor BIO_ADDR_rawaddress$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BIO_ADDR_rawaddress$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_rawaddress",
        constants$129.BIO_ADDR_rawaddress$FUNC, false
    );
    static final FunctionDescriptor BIO_ADDR_rawport$FUNC = FunctionDescriptor.of(JAVA_SHORT,
        ADDRESS
    );
    static final MethodHandle BIO_ADDR_rawport$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_rawport",
        constants$129.BIO_ADDR_rawport$FUNC, false
    );
    static final FunctionDescriptor BIO_ADDR_hostname_string$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle BIO_ADDR_hostname_string$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_hostname_string",
        constants$129.BIO_ADDR_hostname_string$FUNC, false
    );
    static final FunctionDescriptor BIO_ADDR_service_string$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle BIO_ADDR_service_string$MH = RuntimeHelper.downcallHandle(
        "BIO_ADDR_service_string",
        constants$129.BIO_ADDR_service_string$FUNC, false
    );
}


