// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1099 {

    static final FunctionDescriptor ENGINE_unregister_ciphers$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ENGINE_unregister_ciphers$MH = RuntimeHelper.downcallHandle(
        "ENGINE_unregister_ciphers",
        constants$1099.ENGINE_unregister_ciphers$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_all_ciphers$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ENGINE_register_all_ciphers$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_all_ciphers",
        constants$1099.ENGINE_register_all_ciphers$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_digests$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_register_digests$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_digests",
        constants$1099.ENGINE_register_digests$FUNC, false
    );
    static final FunctionDescriptor ENGINE_unregister_digests$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ENGINE_unregister_digests$MH = RuntimeHelper.downcallHandle(
        "ENGINE_unregister_digests",
        constants$1099.ENGINE_unregister_digests$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_all_digests$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ENGINE_register_all_digests$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_all_digests",
        constants$1099.ENGINE_register_all_digests$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_pkey_meths$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_register_pkey_meths$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_pkey_meths",
        constants$1099.ENGINE_register_pkey_meths$FUNC, false
    );
}


