// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1415 {

    static final MemorySegment SN_kx_psk$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("KxPSK");
    static final MemorySegment LN_kx_psk$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("kx-psk");
    static final MemorySegment SN_kx_srp$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("KxSRP");
    static final MemorySegment LN_kx_srp$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("kx-srp");
    static final MemorySegment SN_kx_gost$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("KxGOST");
    static final MemorySegment LN_kx_gost$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("kx-gost");
}


