// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1238 {

    static final MemorySegment SN_id_ppl_anyLanguage$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-ppl-anyLanguage");
    static final MemorySegment LN_id_ppl_anyLanguage$SEGMENT = ResourceScope.globalScope().allocateUtf8String("Any language");
    static final MemorySegment SN_id_ppl_inheritAll$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-ppl-inheritAll");
    static final MemorySegment LN_id_ppl_inheritAll$SEGMENT = ResourceScope.globalScope().allocateUtf8String("Inherit all");
    static final MemorySegment SN_Independent$SEGMENT = ResourceScope.globalScope().allocateUtf8String("id-ppl-independent");
    static final MemorySegment LN_Independent$SEGMENT = ResourceScope.globalScope().allocateUtf8String("Independent");
}


