// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$956 {

    static final FunctionDescriptor sk_DIST_POINT_set_cmp_func$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_DIST_POINT_set_cmp_func$MH = RuntimeHelper.downcallHandle(
        "sk_DIST_POINT_set_cmp_func",
        constants$956.sk_DIST_POINT_set_cmp_func$FUNC, false
    );
    static final FunctionDescriptor sk_SXNETID_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SXNETID_compfunc$MH = RuntimeHelper.downcallHandle(
        constants$956.sk_SXNETID_compfunc$FUNC, false
    );
    static final FunctionDescriptor sk_SXNETID_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SXNETID_freefunc$MH = RuntimeHelper.downcallHandle(
        constants$956.sk_SXNETID_freefunc$FUNC, false
    );
    static final FunctionDescriptor sk_SXNETID_copyfunc$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
}


