// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1110 {

    static final FunctionDescriptor ENGINE_get_pkey_meth$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_pkey_meth$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_pkey_meth",
        constants$1110.ENGINE_get_pkey_meth$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_pkey_asn1_meth$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_pkey_asn1_meth$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_pkey_asn1_meth",
        constants$1110.ENGINE_get_pkey_asn1_meth$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_pkey_asn1_meth_str$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_pkey_asn1_meth_str$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_pkey_asn1_meth_str",
        constants$1110.ENGINE_get_pkey_asn1_meth_str$FUNC, false
    );
    static final FunctionDescriptor ENGINE_pkey_asn1_find_str$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_pkey_asn1_find_str$MH = RuntimeHelper.downcallHandle(
        "ENGINE_pkey_asn1_find_str",
        constants$1110.ENGINE_pkey_asn1_find_str$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_cmd_defns$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_cmd_defns$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_cmd_defns",
        constants$1110.ENGINE_get_cmd_defns$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_flags$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_flags$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_flags",
        constants$1110.ENGINE_get_flags$FUNC, false
    );
}


