// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1321 {

    static final MemorySegment LN_friendlyCountryName$SEGMENT = ResourceScope.globalScope().allocateUtf8String("friendlyCountryName");
    static final MemorySegment SN_uniqueIdentifier$SEGMENT = ResourceScope.globalScope().allocateUtf8String("uid");
    static final MemorySegment LN_uniqueIdentifier$SEGMENT = ResourceScope.globalScope().allocateUtf8String("uniqueIdentifier");
    static final MemorySegment LN_organizationalStatus$SEGMENT = ResourceScope.globalScope().allocateUtf8String("organizationalStatus");
    static final MemorySegment LN_janetMailbox$SEGMENT = ResourceScope.globalScope().allocateUtf8String("janetMailbox");
    static final MemorySegment LN_mailPreferenceOption$SEGMENT = ResourceScope.globalScope().allocateUtf8String("mailPreferenceOption");
}


