// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$233 {

    static final FunctionDescriptor ASN1_TIME_to_tm$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_to_tm$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_to_tm",
        constants$233.ASN1_TIME_to_tm$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_normalize$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_normalize$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_normalize",
        constants$233.ASN1_TIME_normalize$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_cmp_time_t$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle ASN1_TIME_cmp_time_t$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_cmp_time_t",
        constants$233.ASN1_TIME_cmp_time_t$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_compare$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_compare$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_compare",
        constants$233.ASN1_TIME_compare$FUNC, false
    );
    static final FunctionDescriptor i2a_ASN1_INTEGER$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2a_ASN1_INTEGER$MH = RuntimeHelper.downcallHandle(
        "i2a_ASN1_INTEGER",
        constants$233.i2a_ASN1_INTEGER$FUNC, false
    );
    static final FunctionDescriptor a2i_ASN1_INTEGER$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle a2i_ASN1_INTEGER$MH = RuntimeHelper.downcallHandle(
        "a2i_ASN1_INTEGER",
        constants$233.a2i_ASN1_INTEGER$FUNC, false
    );
}


