// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1051 {

    static final FunctionDescriptor sk_ASN1_STRING_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_STRING_compfunc$MH = RuntimeHelper.downcallHandle(
        constants$1051.sk_ASN1_STRING_compfunc$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_STRING_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_ASN1_STRING_freefunc$MH = RuntimeHelper.downcallHandle(
        constants$1051.sk_ASN1_STRING_freefunc$FUNC, false
    );
    static final FunctionDescriptor sk_ASN1_STRING_copyfunc$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_ASN1_STRING_copyfunc$MH = RuntimeHelper.downcallHandle(
        constants$1051.sk_ASN1_STRING_copyfunc$FUNC, false
    );
}


