// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1432 {

    static final MemorySegment PEM_STRING_PARAMETERS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PARAMETERS");
    static final MemorySegment PEM_STRING_CMS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("CMS");
    static final MemorySegment SSL_TXT_LOW$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("LOW");
    static final MemorySegment SSL_TXT_MEDIUM$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("MEDIUM");
    static final MemorySegment SSL_TXT_HIGH$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("HIGH");
    static final MemorySegment SSL_TXT_FIPS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("FIPS");
}


