// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1318 {

    static final MemorySegment SN_secretary$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("secretary");
    static final MemorySegment LN_otherMailbox$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("otherMailbox");
    static final MemorySegment LN_lastModifiedTime$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("lastModifiedTime");
    static final MemorySegment LN_lastModifiedBy$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("lastModifiedBy");
    static final MemorySegment SN_domainComponent$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("DC");
    static final MemorySegment LN_domainComponent$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("domainComponent");
}


