// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$767 {

    static final FunctionDescriptor SSL_CTX_sess_set_new_cb$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_sess_set_new_cb$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_sess_set_new_cb",
        constants$767.SSL_CTX_sess_set_new_cb$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_sess_get_new_cb$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_sess_get_new_cb$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_sess_get_new_cb",
        constants$767.SSL_CTX_sess_get_new_cb$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_sess_set_remove_cb$remove_session_cb$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_sess_set_remove_cb$remove_session_cb$MH = RuntimeHelper.downcallHandle(
        constants$767.SSL_CTX_sess_set_remove_cb$remove_session_cb$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_sess_set_remove_cb$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_sess_set_remove_cb$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_sess_set_remove_cb",
        constants$767.SSL_CTX_sess_set_remove_cb$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_sess_get_remove_cb$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_sess_get_remove_cb$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_sess_get_remove_cb",
        constants$767.SSL_CTX_sess_get_remove_cb$FUNC, false
    );
}


