// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$58 {

    static final FunctionDescriptor sk_OPENSSL_BLOCK_shift$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_OPENSSL_BLOCK_shift$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_shift",
        constants$58.sk_OPENSSL_BLOCK_shift$FUNC, false
    );
    static final FunctionDescriptor sk_OPENSSL_BLOCK_pop_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_OPENSSL_BLOCK_pop_free$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_pop_free",
        constants$58.sk_OPENSSL_BLOCK_pop_free$FUNC, false
    );
    static final FunctionDescriptor sk_OPENSSL_BLOCK_insert$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_OPENSSL_BLOCK_insert$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_insert",
        constants$58.sk_OPENSSL_BLOCK_insert$FUNC, false
    );
    static final FunctionDescriptor sk_OPENSSL_BLOCK_set$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_OPENSSL_BLOCK_set$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_set",
        constants$58.sk_OPENSSL_BLOCK_set$FUNC, false
    );
    static final FunctionDescriptor sk_OPENSSL_BLOCK_find$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_OPENSSL_BLOCK_find$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_find",
        constants$58.sk_OPENSSL_BLOCK_find$FUNC, false
    );
    static final FunctionDescriptor sk_OPENSSL_BLOCK_find_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_OPENSSL_BLOCK_find_ex$MH = RuntimeHelper.downcallHandle(
        "sk_OPENSSL_BLOCK_find_ex",
        constants$58.sk_OPENSSL_BLOCK_find_ex$FUNC, false
    );
}


