// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1014 {

    static final FunctionDescriptor X509V3_EXT_get_nid$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509V3_EXT_get_nid$MH = RuntimeHelper.downcallHandle(
        "X509V3_EXT_get_nid",
        constants$1014.X509V3_EXT_get_nid$FUNC, false
    );
    static final FunctionDescriptor X509V3_add_standard_extensions$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle X509V3_add_standard_extensions$MH = RuntimeHelper.downcallHandle(
        "X509V3_add_standard_extensions",
        constants$1014.X509V3_add_standard_extensions$FUNC, false
    );
    static final FunctionDescriptor X509V3_parse_list$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509V3_parse_list$MH = RuntimeHelper.downcallHandle(
        "X509V3_parse_list",
        constants$1014.X509V3_parse_list$FUNC, false
    );
    static final FunctionDescriptor X509V3_EXT_d2i$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509V3_EXT_d2i$MH = RuntimeHelper.downcallHandle(
        "X509V3_EXT_d2i",
        constants$1014.X509V3_EXT_d2i$FUNC, false
    );
    static final FunctionDescriptor X509V3_get_d2i$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509V3_get_d2i$MH = RuntimeHelper.downcallHandle(
        "X509V3_get_d2i",
        constants$1014.X509V3_get_d2i$FUNC, false
    );
    static final FunctionDescriptor X509V3_EXT_i2d$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509V3_EXT_i2d$MH = RuntimeHelper.downcallHandle(
        "X509V3_EXT_i2d",
        constants$1014.X509V3_EXT_i2d$FUNC, false
    );
}


