// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$85 {

    static final FunctionDescriptor pthread_attr_setscope$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle pthread_attr_setscope$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_setscope",
        constants$85.pthread_attr_setscope$FUNC, false
    );
    static final FunctionDescriptor pthread_attr_getstackaddr$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle pthread_attr_getstackaddr$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_getstackaddr",
        constants$85.pthread_attr_getstackaddr$FUNC, false
    );
    static final FunctionDescriptor pthread_attr_setstackaddr$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle pthread_attr_setstackaddr$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_setstackaddr",
        constants$85.pthread_attr_setstackaddr$FUNC, false
    );
    static final FunctionDescriptor pthread_attr_getstacksize$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle pthread_attr_getstacksize$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_getstacksize",
        constants$85.pthread_attr_getstacksize$FUNC, false
    );
    static final FunctionDescriptor pthread_attr_setstacksize$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle pthread_attr_setstacksize$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_setstacksize",
        constants$85.pthread_attr_setstacksize$FUNC, false
    );
    static final FunctionDescriptor pthread_attr_getstack$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle pthread_attr_getstack$MH = RuntimeHelper.downcallHandle(
        "pthread_attr_getstack",
        constants$85.pthread_attr_getstack$FUNC, false
    );
}


