// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$634 {

    static final FunctionDescriptor i2d_PrivateKey_fp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PrivateKey_fp$MH = RuntimeHelper.downcallHandle(
        "i2d_PrivateKey_fp",
        constants$634.i2d_PrivateKey_fp$FUNC, false
    );
    static final FunctionDescriptor d2i_PrivateKey_fp$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PrivateKey_fp$MH = RuntimeHelper.downcallHandle(
        "d2i_PrivateKey_fp",
        constants$634.d2i_PrivateKey_fp$FUNC, false
    );
    static final FunctionDescriptor i2d_PUBKEY_fp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PUBKEY_fp$MH = RuntimeHelper.downcallHandle(
        "i2d_PUBKEY_fp",
        constants$634.i2d_PUBKEY_fp$FUNC, false
    );
    static final FunctionDescriptor d2i_PUBKEY_fp$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PUBKEY_fp$MH = RuntimeHelper.downcallHandle(
        "d2i_PUBKEY_fp",
        constants$634.d2i_PUBKEY_fp$FUNC, false
    );
    static final FunctionDescriptor d2i_X509_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_X509_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_X509_bio",
        constants$634.d2i_X509_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_X509_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_X509_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_X509_bio",
        constants$634.i2d_X509_bio$FUNC, false
    );
}


