// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$413 {

    static final FunctionDescriptor EC_KEY_METHOD_set_sign$sign$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_set_sign$sign$MH = RuntimeHelper.downcallHandle(
        constants$413.EC_KEY_METHOD_set_sign$sign$FUNC, false
    );
    static final FunctionDescriptor EC_KEY_METHOD_set_sign$sign_setup$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_set_sign$sign_setup$MH = RuntimeHelper.downcallHandle(
        constants$413.EC_KEY_METHOD_set_sign$sign_setup$FUNC, false
    );
    static final FunctionDescriptor EC_KEY_METHOD_set_sign$sign_sig$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_set_sign$sign_sig$MH = RuntimeHelper.downcallHandle(
        constants$413.EC_KEY_METHOD_set_sign$sign_sig$FUNC, false
    );
}


