// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1039 {

    static final FunctionDescriptor sk_IPAddressOrRange_find$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_find$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_find",
        constants$1039.sk_IPAddressOrRange_find$FUNC, false
    );
    static final FunctionDescriptor sk_IPAddressOrRange_find_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_find_ex$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_find_ex",
        constants$1039.sk_IPAddressOrRange_find_ex$FUNC, false
    );
    static final FunctionDescriptor sk_IPAddressOrRange_sort$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_sort$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_sort",
        constants$1039.sk_IPAddressOrRange_sort$FUNC, false
    );
    static final FunctionDescriptor sk_IPAddressOrRange_is_sorted$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_is_sorted$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_is_sorted",
        constants$1039.sk_IPAddressOrRange_is_sorted$FUNC, false
    );
    static final FunctionDescriptor sk_IPAddressOrRange_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_dup$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_dup",
        constants$1039.sk_IPAddressOrRange_dup$FUNC, false
    );
    static final FunctionDescriptor sk_IPAddressOrRange_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_IPAddressOrRange_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_IPAddressOrRange_deep_copy",
        constants$1039.sk_IPAddressOrRange_deep_copy$FUNC, false
    );
}


