// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1097 {

    static final FunctionDescriptor ENGINE_unregister_DSA$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ENGINE_unregister_DSA$MH = RuntimeHelper.downcallHandle(
        "ENGINE_unregister_DSA",
        constants$1097.ENGINE_unregister_DSA$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_all_DSA$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ENGINE_register_all_DSA$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_all_DSA",
        constants$1097.ENGINE_register_all_DSA$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_EC$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_register_EC$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_EC",
        constants$1097.ENGINE_register_EC$FUNC, false
    );
    static final FunctionDescriptor ENGINE_unregister_EC$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ENGINE_unregister_EC$MH = RuntimeHelper.downcallHandle(
        "ENGINE_unregister_EC",
        constants$1097.ENGINE_unregister_EC$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_all_EC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ENGINE_register_all_EC$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_all_EC",
        constants$1097.ENGINE_register_all_EC$FUNC, false
    );
    static final FunctionDescriptor ENGINE_register_DH$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_register_DH$MH = RuntimeHelper.downcallHandle(
        "ENGINE_register_DH",
        constants$1097.ENGINE_register_DH$FUNC, false
    );
}


