// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1091 {

    static final FunctionDescriptor UI_UTIL_read_pw_string$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle UI_UTIL_read_pw_string$MH = RuntimeHelper.downcallHandle(
        "UI_UTIL_read_pw_string",
        constants$1091.UI_UTIL_read_pw_string$FUNC, false
    );
    static final FunctionDescriptor UI_UTIL_read_pw$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle UI_UTIL_read_pw$MH = RuntimeHelper.downcallHandle(
        "UI_UTIL_read_pw",
        constants$1091.UI_UTIL_read_pw$FUNC, false
    );
    static final FunctionDescriptor UI_UTIL_wrap_read_pem_callback$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle UI_UTIL_wrap_read_pem_callback$MH = RuntimeHelper.downcallHandle(
        "UI_UTIL_wrap_read_pem_callback",
        constants$1091.UI_UTIL_wrap_read_pem_callback$FUNC, false
    );
    static final FunctionDescriptor ERR_load_ENGINE_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_ENGINE_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_ENGINE_strings",
        constants$1091.ERR_load_ENGINE_strings$FUNC, false
    );
    static final FunctionDescriptor ENGINE_GEN_FUNC_PTR$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ENGINE_GEN_FUNC_PTR$MH = RuntimeHelper.downcallHandle(
        constants$1091.ENGINE_GEN_FUNC_PTR$FUNC, false
    );
}


