// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1325 {

    static final MemorySegment LN_set_certExt$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("certificate extensions");
    static final MemorySegment SN_set_brand$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("set-brand");
    static final MemorySegment SN_setct_PANData$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("setct-PANData");
    static final MemorySegment SN_setct_PANToken$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("setct-PANToken");
    static final MemorySegment SN_setct_PANOnly$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("setct-PANOnly");
    static final MemorySegment SN_setct_OIData$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("setct-OIData");
}


