// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$825 {

    static final FunctionDescriptor SSL_get0_param$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_get0_param$MH = RuntimeHelper.downcallHandle(
        "SSL_get0_param",
        constants$825.SSL_get0_param$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_srp_username$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_set_srp_username$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_set_srp_username",
        constants$825.SSL_CTX_set_srp_username$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_srp_password$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_set_srp_password$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_set_srp_password",
        constants$825.SSL_CTX_set_srp_password$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_srp_strength$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle SSL_CTX_set_srp_strength$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_set_srp_strength",
        constants$825.SSL_CTX_set_srp_strength$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_srp_client_pwd_callback$cb$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_set_srp_client_pwd_callback$cb$MH = RuntimeHelper.downcallHandle(
        constants$825.SSL_CTX_set_srp_client_pwd_callback$cb$FUNC, false
    );
}


