// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$872 {

    static final FunctionDescriptor lh_ERR_STRING_DATA_error$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_error$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_error",
        constants$872.lh_ERR_STRING_DATA_error$FUNC, false
    );
    static final FunctionDescriptor lh_ERR_STRING_DATA_num_items$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_num_items$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_num_items",
        constants$872.lh_ERR_STRING_DATA_num_items$FUNC, false
    );
    static final FunctionDescriptor lh_ERR_STRING_DATA_node_stats_bio$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_node_stats_bio$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_node_stats_bio",
        constants$872.lh_ERR_STRING_DATA_node_stats_bio$FUNC, false
    );
    static final FunctionDescriptor lh_ERR_STRING_DATA_node_usage_stats_bio$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_node_usage_stats_bio$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_node_usage_stats_bio",
        constants$872.lh_ERR_STRING_DATA_node_usage_stats_bio$FUNC, false
    );
    static final FunctionDescriptor lh_ERR_STRING_DATA_stats_bio$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_stats_bio$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_stats_bio",
        constants$872.lh_ERR_STRING_DATA_stats_bio$FUNC, false
    );
    static final FunctionDescriptor lh_ERR_STRING_DATA_get_down_load$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle lh_ERR_STRING_DATA_get_down_load$MH = RuntimeHelper.downcallHandle(
        "lh_ERR_STRING_DATA_get_down_load",
        constants$872.lh_ERR_STRING_DATA_get_down_load$FUNC, false
    );
}


