// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$239 {

    static final FunctionDescriptor ASN1_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_dup$MH = RuntimeHelper.downcallHandle(
        "ASN1_dup",
        constants$239.ASN1_dup$FUNC, false
    );
    static final FunctionDescriptor ASN1_item_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_item_dup$MH = RuntimeHelper.downcallHandle(
        "ASN1_item_dup",
        constants$239.ASN1_item_dup$FUNC, false
    );
    static final FunctionDescriptor ASN1_d2i_fp$xnew$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ASN1_d2i_fp$xnew$MH = RuntimeHelper.downcallHandle(
        constants$239.ASN1_d2i_fp$xnew$FUNC, false
    );
    static final FunctionDescriptor ASN1_d2i_fp$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_d2i_fp$MH = RuntimeHelper.downcallHandle(
        "ASN1_d2i_fp",
        constants$239.ASN1_d2i_fp$FUNC, false
    );
    static final FunctionDescriptor ASN1_item_d2i_fp$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_item_d2i_fp$MH = RuntimeHelper.downcallHandle(
        "ASN1_item_d2i_fp",
        constants$239.ASN1_item_d2i_fp$FUNC, false
    );
}


