// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$707 {

    static final FunctionDescriptor X509_TRUST_get_by_id$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle X509_TRUST_get_by_id$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_get_by_id",
        constants$707.X509_TRUST_get_by_id$FUNC, false
    );
    static final FunctionDescriptor X509_TRUST_add$ck$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_TRUST_add$ck$MH = RuntimeHelper.downcallHandle(
        constants$707.X509_TRUST_add$ck$FUNC, false
    );
    static final FunctionDescriptor X509_TRUST_add$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_TRUST_add$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_add",
        constants$707.X509_TRUST_add$FUNC, false
    );
    static final FunctionDescriptor X509_TRUST_cleanup$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle X509_TRUST_cleanup$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_cleanup",
        constants$707.X509_TRUST_cleanup$FUNC, false
    );
    static final FunctionDescriptor X509_TRUST_get_flags$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_TRUST_get_flags$MH = RuntimeHelper.downcallHandle(
        "X509_TRUST_get_flags",
        constants$707.X509_TRUST_get_flags$FUNC, false
    );
}


