// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$315 {

    static final FunctionDescriptor EVP_camellia_192_cfb1$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_192_cfb1$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_192_cfb1",
        constants$315.EVP_camellia_192_cfb1$FUNC, false
    );
    static final FunctionDescriptor EVP_camellia_192_cfb8$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_192_cfb8$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_192_cfb8",
        constants$315.EVP_camellia_192_cfb8$FUNC, false
    );
    static final FunctionDescriptor EVP_camellia_192_cfb128$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_192_cfb128$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_192_cfb128",
        constants$315.EVP_camellia_192_cfb128$FUNC, false
    );
    static final FunctionDescriptor EVP_camellia_192_ofb$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_192_ofb$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_192_ofb",
        constants$315.EVP_camellia_192_ofb$FUNC, false
    );
    static final FunctionDescriptor EVP_camellia_192_ctr$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_192_ctr$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_192_ctr",
        constants$315.EVP_camellia_192_ctr$FUNC, false
    );
    static final FunctionDescriptor EVP_camellia_256_ecb$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_camellia_256_ecb$MH = RuntimeHelper.downcallHandle(
        "EVP_camellia_256_ecb",
        constants$315.EVP_camellia_256_ecb$FUNC, false
    );
}


