// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1362 {

    static final MemorySegment LN_id_GostR3410_2012_512$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("GOST R 34.10-2012 with 512 bit modulus");
    static final MemorySegment SN_id_tc26_digest$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("id-tc26-digest");
    static final MemorySegment SN_id_GostR3411_2012_256$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("md_gost12_256");
    static final MemorySegment LN_id_GostR3411_2012_256$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("GOST R 34.11-2012 with 256 bit hash");
    static final MemorySegment SN_id_GostR3411_2012_512$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("md_gost12_512");
    static final MemorySegment LN_id_GostR3411_2012_512$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("GOST R 34.11-2012 with 512 bit hash");
}


