// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$579 {

    static final FunctionDescriptor X509_STORE_set_default_paths$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_set_default_paths$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_set_default_paths",
        constants$579.X509_STORE_set_default_paths$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_set_ex_data",
        constants$579.X509_STORE_CTX_set_ex_data$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_STORE_CTX_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_ex_data",
        constants$579.X509_STORE_CTX_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_error$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_error$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_error",
        constants$579.X509_STORE_CTX_get_error$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_set_error$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_STORE_CTX_set_error$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_set_error",
        constants$579.X509_STORE_CTX_set_error$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_error_depth$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_error_depth$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_error_depth",
        constants$579.X509_STORE_CTX_get_error_depth$FUNC, false
    );
}


