// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$375 {

    static final FunctionDescriptor EVP_PKEY_meth_get_signctx$psignctx$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_signctx$psignctx$MH = RuntimeHelper.downcallHandle(
        constants$375.EVP_PKEY_meth_get_signctx$psignctx$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_signctx$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_signctx$MH = RuntimeHelper.downcallHandle(
        "EVP_PKEY_meth_get_signctx",
        constants$375.EVP_PKEY_meth_get_signctx$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_verifyctx$pverifyctx_init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_verifyctx$pverifyctx_init$MH = RuntimeHelper.downcallHandle(
        constants$375.EVP_PKEY_meth_get_verifyctx$pverifyctx_init$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_verifyctx$pverifyctx$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_verifyctx$pverifyctx$MH = RuntimeHelper.downcallHandle(
        constants$375.EVP_PKEY_meth_get_verifyctx$pverifyctx$FUNC, false
    );
}


