// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$637 {

    static final FunctionDescriptor d2i_DSAPrivateKey_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_DSAPrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_DSAPrivateKey_bio",
        constants$637.d2i_DSAPrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_DSAPrivateKey_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_DSAPrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_DSAPrivateKey_bio",
        constants$637.i2d_DSAPrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor d2i_EC_PUBKEY_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_EC_PUBKEY_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_EC_PUBKEY_bio",
        constants$637.d2i_EC_PUBKEY_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_EC_PUBKEY_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_EC_PUBKEY_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_EC_PUBKEY_bio",
        constants$637.i2d_EC_PUBKEY_bio$FUNC, false
    );
    static final FunctionDescriptor d2i_ECPrivateKey_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_ECPrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_ECPrivateKey_bio",
        constants$637.d2i_ECPrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_ECPrivateKey_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_ECPrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_ECPrivateKey_bio",
        constants$637.i2d_ECPrivateKey_bio$FUNC, false
    );
}


