// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$736 {

    static final FunctionDescriptor sk_SCT_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_SCT_freefunc$MH = RuntimeHelper.downcallHandle(
        constants$736.sk_SCT_freefunc$FUNC, false
    );
    static final FunctionDescriptor sk_SCT_copyfunc$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_SCT_copyfunc$MH = RuntimeHelper.downcallHandle(
        constants$736.sk_SCT_copyfunc$FUNC, false
    );
    static final FunctionDescriptor sk_SCT_num$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_SCT_num$MH = RuntimeHelper.downcallHandle(
        "sk_SCT_num",
        constants$736.sk_SCT_num$FUNC, false
    );
    static final FunctionDescriptor sk_SCT_value$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_SCT_value$MH = RuntimeHelper.downcallHandle(
        "sk_SCT_value",
        constants$736.sk_SCT_value$FUNC, false
    );
}


