// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$529 {

    static final FunctionDescriptor OPENSSL_LH_doall_arg$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle OPENSSL_LH_doall_arg$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_doall_arg",
        constants$529.OPENSSL_LH_doall_arg$FUNC, false
    );
    static final FunctionDescriptor OPENSSL_LH_strhash$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle OPENSSL_LH_strhash$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_strhash",
        constants$529.OPENSSL_LH_strhash$FUNC, false
    );
    static final FunctionDescriptor OPENSSL_LH_num_items$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle OPENSSL_LH_num_items$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_num_items",
        constants$529.OPENSSL_LH_num_items$FUNC, false
    );
    static final FunctionDescriptor OPENSSL_LH_get_down_load$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle OPENSSL_LH_get_down_load$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_get_down_load",
        constants$529.OPENSSL_LH_get_down_load$FUNC, false
    );
    static final FunctionDescriptor OPENSSL_LH_set_down_load$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle OPENSSL_LH_set_down_load$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_set_down_load",
        constants$529.OPENSSL_LH_set_down_load$FUNC, false
    );
    static final FunctionDescriptor OPENSSL_LH_stats$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle OPENSSL_LH_stats$MH = RuntimeHelper.downcallHandle(
        "OPENSSL_LH_stats",
        constants$529.OPENSSL_LH_stats$FUNC, false
    );
}


