// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$566 {

    static final FunctionDescriptor X509_STORE_CTX_get0_store$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get0_store$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get0_store",
        constants$566.X509_STORE_CTX_get0_store$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get0_cert$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get0_cert$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get0_cert",
        constants$566.X509_STORE_CTX_get0_cert$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get0_untrusted$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get0_untrusted$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get0_untrusted",
        constants$566.X509_STORE_CTX_get0_untrusted$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_set0_untrusted$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_set0_untrusted$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_set0_untrusted",
        constants$566.X509_STORE_CTX_set0_untrusted$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_set_verify_cb$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_set_verify_cb$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_set_verify_cb",
        constants$566.X509_STORE_CTX_set_verify_cb$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_verify_cb$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_verify_cb$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_verify_cb",
        constants$566.X509_STORE_CTX_get_verify_cb$FUNC, false
    );
}


