// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1436 {

    static final MemorySegment SSL_TXT_kGOST$SEGMENT = ResourceScope.globalScope().allocateUtf8String("kGOST");
    static final MemorySegment SSL_TXT_kSRP$SEGMENT = ResourceScope.globalScope().allocateUtf8String("kSRP");
    static final MemorySegment SSL_TXT_aRSA$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aRSA");
    static final MemorySegment SSL_TXT_aDSS$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aDSS");
    static final MemorySegment SSL_TXT_aDH$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aDH");
    static final MemorySegment SSL_TXT_aECDH$SEGMENT = ResourceScope.globalScope().allocateUtf8String("aECDH");
}


