// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$698 {

    static final FunctionDescriptor X509_ATTRIBUTE_set1_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_ATTRIBUTE_set1_data$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_set1_data",
        constants$698.X509_ATTRIBUTE_set1_data$FUNC, false
    );
    static final FunctionDescriptor X509_ATTRIBUTE_get0_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_ATTRIBUTE_get0_data$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_get0_data",
        constants$698.X509_ATTRIBUTE_get0_data$FUNC, false
    );
    static final FunctionDescriptor X509_ATTRIBUTE_count$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_ATTRIBUTE_count$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_count",
        constants$698.X509_ATTRIBUTE_count$FUNC, false
    );
    static final FunctionDescriptor X509_ATTRIBUTE_get0_object$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_ATTRIBUTE_get0_object$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_get0_object",
        constants$698.X509_ATTRIBUTE_get0_object$FUNC, false
    );
    static final FunctionDescriptor X509_ATTRIBUTE_get0_type$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_ATTRIBUTE_get0_type$MH = RuntimeHelper.downcallHandle(
        "X509_ATTRIBUTE_get0_type",
        constants$698.X509_ATTRIBUTE_get0_type$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_get_attr_count$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_get_attr_count$MH = RuntimeHelper.downcallHandle(
        "EVP_PKEY_get_attr_count",
        constants$698.EVP_PKEY_get_attr_count$FUNC, false
    );
}


