// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$682 {

    static final FunctionDescriptor X509_NAME_cmp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_NAME_cmp$MH = RuntimeHelper.downcallHandle(
        "X509_NAME_cmp",
        constants$682.X509_NAME_cmp$FUNC, false
    );
    static final FunctionDescriptor X509_NAME_hash$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle X509_NAME_hash$MH = RuntimeHelper.downcallHandle(
        "X509_NAME_hash",
        constants$682.X509_NAME_hash$FUNC, false
    );
    static final FunctionDescriptor X509_NAME_hash_old$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle X509_NAME_hash_old$MH = RuntimeHelper.downcallHandle(
        "X509_NAME_hash_old",
        constants$682.X509_NAME_hash_old$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_cmp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_CRL_cmp$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_cmp",
        constants$682.X509_CRL_cmp$FUNC, false
    );
    static final FunctionDescriptor X509_CRL_match$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_CRL_match$MH = RuntimeHelper.downcallHandle(
        "X509_CRL_match",
        constants$682.X509_CRL_match$FUNC, false
    );
    static final FunctionDescriptor X509_aux_print$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_aux_print$MH = RuntimeHelper.downcallHandle(
        "X509_aux_print",
        constants$682.X509_aux_print$FUNC, false
    );
}


