// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$32 {

    static final FunctionDescriptor getchar_unlocked$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle getchar_unlocked$MH = RuntimeHelper.downcallHandle(
        "getchar_unlocked",
        constants$32.getchar_unlocked$FUNC, false
    );
    static final FunctionDescriptor fgetc_unlocked$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle fgetc_unlocked$MH = RuntimeHelper.downcallHandle(
        "fgetc_unlocked",
        constants$32.fgetc_unlocked$FUNC, false
    );
    static final FunctionDescriptor fputc$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle fputc$MH = RuntimeHelper.downcallHandle(
        "fputc",
        constants$32.fputc$FUNC, false
    );
    static final FunctionDescriptor putc$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle putc$MH = RuntimeHelper.downcallHandle(
        "putc",
        constants$32.putc$FUNC, false
    );
    static final FunctionDescriptor putchar$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle putchar$MH = RuntimeHelper.downcallHandle(
        "putchar",
        constants$32.putchar$FUNC, false
    );
    static final FunctionDescriptor fputc_unlocked$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle fputc_unlocked$MH = RuntimeHelper.downcallHandle(
        "fputc_unlocked",
        constants$32.fputc_unlocked$FUNC, false
    );
}


