// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1344 {

    static final MemorySegment SN_setAttr_Token_EMV$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-Token-EMV");
    static final MemorySegment SN_setAttr_Token_B0Prime$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-Token-B0Prime");
    static final MemorySegment SN_setAttr_IssCap_CVM$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-IssCap-CVM");
    static final MemorySegment SN_setAttr_IssCap_T2$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-IssCap-T2");
    static final MemorySegment SN_setAttr_IssCap_Sig$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-IssCap-Sig");
    static final MemorySegment SN_setAttr_GenCryptgrm$SEGMENT = ResourceScope.globalScope().allocateUtf8String("setAttr-GenCryptgrm");
}


