// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$814 {

    static final FunctionDescriptor SSL_SESSION_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle SSL_SESSION_free$MH = RuntimeHelper.downcallHandle(
        "SSL_SESSION_free",
        constants$814.SSL_SESSION_free$FUNC, false
    );
    static final FunctionDescriptor i2d_SSL_SESSION$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_SSL_SESSION$MH = RuntimeHelper.downcallHandle(
        "i2d_SSL_SESSION",
        constants$814.i2d_SSL_SESSION$FUNC, false
    );
    static final FunctionDescriptor SSL_set_session$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_set_session$MH = RuntimeHelper.downcallHandle(
        "SSL_set_session",
        constants$814.SSL_set_session$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_add_session$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_add_session$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_add_session",
        constants$814.SSL_CTX_add_session$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_remove_session$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_remove_session$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_remove_session",
        constants$814.SSL_CTX_remove_session$FUNC, false
    );
    static final FunctionDescriptor SSL_CTX_set_generate_session_id$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_CTX_set_generate_session_id$MH = RuntimeHelper.downcallHandle(
        "SSL_CTX_set_generate_session_id",
        constants$814.SSL_CTX_set_generate_session_id$FUNC, false
    );
}


