// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$999 {

    static final FunctionDescriptor i2d_CERTIFICATEPOLICIES$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_CERTIFICATEPOLICIES$MH = RuntimeHelper.downcallHandle(
        "i2d_CERTIFICATEPOLICIES",
        constants$999.i2d_CERTIFICATEPOLICIES$FUNC, false
    );
    static final FunctionDescriptor POLICYINFO_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle POLICYINFO_new$MH = RuntimeHelper.downcallHandle(
        "POLICYINFO_new",
        constants$999.POLICYINFO_new$FUNC, false
    );
    static final FunctionDescriptor POLICYINFO_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle POLICYINFO_free$MH = RuntimeHelper.downcallHandle(
        "POLICYINFO_free",
        constants$999.POLICYINFO_free$FUNC, false
    );
    static final FunctionDescriptor d2i_POLICYINFO$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_POLICYINFO$MH = RuntimeHelper.downcallHandle(
        "d2i_POLICYINFO",
        constants$999.d2i_POLICYINFO$FUNC, false
    );
    static final FunctionDescriptor i2d_POLICYINFO$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_POLICYINFO$MH = RuntimeHelper.downcallHandle(
        "i2d_POLICYINFO",
        constants$999.i2d_POLICYINFO$FUNC, false
    );
    static final FunctionDescriptor POLICYQUALINFO_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle POLICYQUALINFO_new$MH = RuntimeHelper.downcallHandle(
        "POLICYQUALINFO_new",
        constants$999.POLICYQUALINFO_new$FUNC, false
    );
}


