// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$906 {

    static final FunctionDescriptor sk_CONF_VALUE_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_VALUE_dup$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_VALUE_dup",
        constants$906.sk_CONF_VALUE_dup$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_VALUE_deep_copy$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_VALUE_deep_copy$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_VALUE_deep_copy",
        constants$906.sk_CONF_VALUE_deep_copy$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_VALUE_set_cmp_func$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_VALUE_set_cmp_func$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_VALUE_set_cmp_func",
        constants$906.sk_CONF_VALUE_set_cmp_func$FUNC, false
    );
    static final FunctionDescriptor lh_CONF_VALUE_new$hfn$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle lh_CONF_VALUE_new$hfn$MH = RuntimeHelper.downcallHandle(
        constants$906.lh_CONF_VALUE_new$hfn$FUNC, false
    );
    static final FunctionDescriptor lh_CONF_VALUE_new$cfn$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
}


