// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$663 {

    static final FunctionDescriptor X509_PKEY_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle X509_PKEY_free$MH = RuntimeHelper.downcallHandle(
        "X509_PKEY_free",
        constants$663.X509_PKEY_free$FUNC, false
    );
    static final FunctionDescriptor NETSCAPE_SPKI_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle NETSCAPE_SPKI_new$MH = RuntimeHelper.downcallHandle(
        "NETSCAPE_SPKI_new",
        constants$663.NETSCAPE_SPKI_new$FUNC, false
    );
    static final FunctionDescriptor NETSCAPE_SPKI_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle NETSCAPE_SPKI_free$MH = RuntimeHelper.downcallHandle(
        "NETSCAPE_SPKI_free",
        constants$663.NETSCAPE_SPKI_free$FUNC, false
    );
    static final FunctionDescriptor d2i_NETSCAPE_SPKI$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_NETSCAPE_SPKI$MH = RuntimeHelper.downcallHandle(
        "d2i_NETSCAPE_SPKI",
        constants$663.d2i_NETSCAPE_SPKI$FUNC, false
    );
    static final FunctionDescriptor i2d_NETSCAPE_SPKI$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_NETSCAPE_SPKI$MH = RuntimeHelper.downcallHandle(
        "i2d_NETSCAPE_SPKI",
        constants$663.i2d_NETSCAPE_SPKI$FUNC, false
    );
    static final FunctionDescriptor NETSCAPE_SPKAC_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle NETSCAPE_SPKAC_new$MH = RuntimeHelper.downcallHandle(
        "NETSCAPE_SPKAC_new",
        constants$663.NETSCAPE_SPKAC_new$FUNC, false
    );
}


