// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1111 {

    static final FunctionDescriptor ENGINE_init$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_init$MH = RuntimeHelper.downcallHandle(
        "ENGINE_init",
        constants$1111.ENGINE_init$FUNC, false
    );
    static final FunctionDescriptor ENGINE_finish$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_finish$MH = RuntimeHelper.downcallHandle(
        "ENGINE_finish",
        constants$1111.ENGINE_finish$FUNC, false
    );
    static final FunctionDescriptor ENGINE_load_private_key$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_load_private_key$MH = RuntimeHelper.downcallHandle(
        "ENGINE_load_private_key",
        constants$1111.ENGINE_load_private_key$FUNC, false
    );
    static final FunctionDescriptor ENGINE_load_public_key$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_load_public_key$MH = RuntimeHelper.downcallHandle(
        "ENGINE_load_public_key",
        constants$1111.ENGINE_load_public_key$FUNC, false
    );
    static final FunctionDescriptor ENGINE_load_ssl_client_cert$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_load_ssl_client_cert$MH = RuntimeHelper.downcallHandle(
        "ENGINE_load_ssl_client_cert",
        constants$1111.ENGINE_load_ssl_client_cert$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_default_RSA$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ENGINE_get_default_RSA$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_default_RSA",
        constants$1111.ENGINE_get_default_RSA$FUNC, false
    );
}


