// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$605 {

    static final FunctionDescriptor sk_PKCS7_pop_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_pop_free$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_pop_free",
        constants$605.sk_PKCS7_pop_free$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_insert$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_PKCS7_insert$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_insert",
        constants$605.sk_PKCS7_insert$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_set$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_set$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_set",
        constants$605.sk_PKCS7_set$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_find$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_find$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_find",
        constants$605.sk_PKCS7_find$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_find_ex$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_find_ex$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_find_ex",
        constants$605.sk_PKCS7_find_ex$FUNC, false
    );
    static final FunctionDescriptor sk_PKCS7_sort$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle sk_PKCS7_sort$MH = RuntimeHelper.downcallHandle(
        "sk_PKCS7_sort",
        constants$605.sk_PKCS7_sort$FUNC, false
    );
}


