// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$470 {

    static final FunctionDescriptor DSA_meth_new$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle DSA_meth_new$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_new",
        constants$470.DSA_meth_new$FUNC, false
    );
    static final FunctionDescriptor DSA_meth_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle DSA_meth_free$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_free",
        constants$470.DSA_meth_free$FUNC, false
    );
    static final FunctionDescriptor DSA_meth_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle DSA_meth_dup$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_dup",
        constants$470.DSA_meth_dup$FUNC, false
    );
    static final FunctionDescriptor DSA_meth_get0_name$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle DSA_meth_get0_name$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_get0_name",
        constants$470.DSA_meth_get0_name$FUNC, false
    );
    static final FunctionDescriptor DSA_meth_set1_name$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle DSA_meth_set1_name$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_set1_name",
        constants$470.DSA_meth_set1_name$FUNC, false
    );
    static final FunctionDescriptor DSA_meth_get_flags$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DSA_meth_get_flags$MH = RuntimeHelper.downcallHandle(
        "DSA_meth_get_flags",
        constants$470.DSA_meth_get_flags$FUNC, false
    );
}


