// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1106 {

    static final FunctionDescriptor ENGINE_set_flags$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_set_flags$MH = RuntimeHelper.downcallHandle(
        "ENGINE_set_flags",
        constants$1106.ENGINE_set_flags$FUNC, false
    );
    static final FunctionDescriptor ENGINE_set_cmd_defns$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_set_cmd_defns$MH = RuntimeHelper.downcallHandle(
        "ENGINE_set_cmd_defns",
        constants$1106.ENGINE_set_cmd_defns$FUNC, false
    );
    static final FunctionDescriptor ENGINE_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ENGINE_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "ENGINE_set_ex_data",
        constants$1106.ENGINE_set_ex_data$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle ENGINE_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_ex_data",
        constants$1106.ENGINE_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_id$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_id$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_id",
        constants$1106.ENGINE_get_id$FUNC, false
    );
    static final FunctionDescriptor ENGINE_get_name$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle ENGINE_get_name$MH = RuntimeHelper.downcallHandle(
        "ENGINE_get_name",
        constants$1106.ENGINE_get_name$FUNC, false
    );
}


