// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$878 {

    static final FunctionDescriptor ERR_unload_strings$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ERR_unload_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_unload_strings",
        constants$878.ERR_unload_strings$FUNC, false
    );
    static final FunctionDescriptor ERR_load_ERR_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_ERR_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_ERR_strings",
        constants$878.ERR_load_ERR_strings$FUNC, false
    );
    static final FunctionDescriptor ERR_remove_thread_state$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle ERR_remove_thread_state$MH = RuntimeHelper.downcallHandle(
        "ERR_remove_thread_state",
        constants$878.ERR_remove_thread_state$FUNC, false
    );
    static final FunctionDescriptor ERR_remove_state$FUNC = FunctionDescriptor.ofVoid(
        JAVA_LONG
    );
    static final MethodHandle ERR_remove_state$MH = RuntimeHelper.downcallHandle(
        "ERR_remove_state",
        constants$878.ERR_remove_state$FUNC, false
    );
    static final FunctionDescriptor ERR_get_state$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle ERR_get_state$MH = RuntimeHelper.downcallHandle(
        "ERR_get_state",
        constants$878.ERR_get_state$FUNC, false
    );
    static final FunctionDescriptor ERR_get_next_error_library$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_get_next_error_library$MH = RuntimeHelper.downcallHandle(
        "ERR_get_next_error_library",
        constants$878.ERR_get_next_error_library$FUNC, false
    );
}


