// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$28 {

    static final FunctionDescriptor setbuf$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle setbuf$MH = RuntimeHelper.downcallHandle(
        "setbuf",
        constants$28.setbuf$FUNC, false
    );
    static final FunctionDescriptor setvbuf$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle setvbuf$MH = RuntimeHelper.downcallHandle(
        "setvbuf",
        constants$28.setvbuf$FUNC, false
    );
    static final FunctionDescriptor setbuffer$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle setbuffer$MH = RuntimeHelper.downcallHandle(
        "setbuffer",
        constants$28.setbuffer$FUNC, false
    );
    static final FunctionDescriptor setlinebuf$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle setlinebuf$MH = RuntimeHelper.downcallHandle(
        "setlinebuf",
        constants$28.setlinebuf$FUNC, false
    );
    static final FunctionDescriptor fprintf$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle fprintf$MH = RuntimeHelper.downcallHandle(
        "fprintf",
        constants$28.fprintf$FUNC, true
    );
    static final FunctionDescriptor printf$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle printf$MH = RuntimeHelper.downcallHandle(
        "printf",
        constants$28.printf$FUNC, true
    );
}


