// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$7 {

    static final FunctionDescriptor X509_LOOKUP_ctrl$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle X509_LOOKUP_ctrl$MH = RuntimeHelper.downcallHandle(
        "X509_LOOKUP_ctrl",
        constants$7.X509_LOOKUP_ctrl$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_STORE_CTX_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_ex_data",
        constants$7.X509_STORE_CTX_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_error$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_error$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_error",
        constants$7.X509_STORE_CTX_get_error$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_set_error$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle X509_STORE_CTX_set_error$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_set_error",
        constants$7.X509_STORE_CTX_set_error$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_error_depth$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_error_depth$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_error_depth",
        constants$7.X509_STORE_CTX_get_error_depth$FUNC, false
    );
    static final FunctionDescriptor X509_STORE_CTX_get_current_cert$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle X509_STORE_CTX_get_current_cert$MH = RuntimeHelper.downcallHandle(
        "X509_STORE_CTX_get_current_cert",
        constants$7.X509_STORE_CTX_get_current_cert$FUNC, false
    );
}


