// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$481 {

    static final FunctionDescriptor SHA512$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle SHA512$MH = RuntimeHelper.downcallHandle(
        "SHA512",
        constants$481.SHA512$FUNC, false
    );
    static final FunctionDescriptor SHA512_Transform$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle SHA512_Transform$MH = RuntimeHelper.downcallHandle(
        "SHA512_Transform",
        constants$481.SHA512_Transform$FUNC, false
    );
    static final FunctionDescriptor ERR_load_X509_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_X509_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_X509_strings",
        constants$481.ERR_load_X509_strings$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_ENTRY_compfunc$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_X509_NAME_ENTRY_compfunc$MH = RuntimeHelper.downcallHandle(
        constants$481.sk_X509_NAME_ENTRY_compfunc$FUNC, false
    );
    static final FunctionDescriptor sk_X509_NAME_ENTRY_freefunc$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
}


