// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$144 {

    static final FunctionDescriptor BUF_MEM_grow_clean$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle BUF_MEM_grow_clean$MH = RuntimeHelper.downcallHandle(
        "BUF_MEM_grow_clean",
        constants$144.BUF_MEM_grow_clean$FUNC, false
    );
    static final FunctionDescriptor BUF_reverse$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle BUF_reverse$MH = RuntimeHelper.downcallHandle(
        "BUF_reverse",
        constants$144.BUF_reverse$FUNC, false
    );
    static final FunctionDescriptor ERR_load_EVP_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_EVP_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_EVP_strings",
        constants$144.ERR_load_EVP_strings$FUNC, false
    );
    static final FunctionDescriptor ERR_load_ASN1_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_ASN1_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_ASN1_strings",
        constants$144.ERR_load_ASN1_strings$FUNC, false
    );
    static final FunctionDescriptor ERR_load_BN_strings$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle ERR_load_BN_strings$MH = RuntimeHelper.downcallHandle(
        "ERR_load_BN_strings",
        constants$144.ERR_load_BN_strings$FUNC, false
    );
    static final FunctionDescriptor BN_set_flags$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle BN_set_flags$MH = RuntimeHelper.downcallHandle(
        "BN_set_flags",
        constants$144.BN_set_flags$FUNC, false
    );
}


