// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$917 {

    static final FunctionDescriptor sk_CONF_IMODULE_delete$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle sk_CONF_IMODULE_delete$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_delete",
        constants$917.sk_CONF_IMODULE_delete$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_IMODULE_delete_ptr$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_IMODULE_delete_ptr$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_delete_ptr",
        constants$917.sk_CONF_IMODULE_delete_ptr$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_IMODULE_push$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_IMODULE_push$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_push",
        constants$917.sk_CONF_IMODULE_push$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_IMODULE_unshift$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_IMODULE_unshift$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_unshift",
        constants$917.sk_CONF_IMODULE_unshift$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_IMODULE_pop$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_IMODULE_pop$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_pop",
        constants$917.sk_CONF_IMODULE_pop$FUNC, false
    );
    static final FunctionDescriptor sk_CONF_IMODULE_shift$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle sk_CONF_IMODULE_shift$MH = RuntimeHelper.downcallHandle(
        "sk_CONF_IMODULE_shift",
        constants$917.sk_CONF_IMODULE_shift$FUNC, false
    );
}


