// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$232 {

    static final FunctionDescriptor ASN1_TIME_set$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle ASN1_TIME_set$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_set",
        constants$232.ASN1_TIME_set$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_adj$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_LONG,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle ASN1_TIME_adj$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_adj",
        constants$232.ASN1_TIME_adj$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_check$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_check$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_check",
        constants$232.ASN1_TIME_check$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_to_generalizedtime$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_to_generalizedtime$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_to_generalizedtime",
        constants$232.ASN1_TIME_to_generalizedtime$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_set_string$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_set_string$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_set_string",
        constants$232.ASN1_TIME_set_string$FUNC, false
    );
    static final FunctionDescriptor ASN1_TIME_set_string_X509$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle ASN1_TIME_set_string_X509$MH = RuntimeHelper.downcallHandle(
        "ASN1_TIME_set_string_X509",
        constants$232.ASN1_TIME_set_string_X509$FUNC, false
    );
}


