// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$169 {

    static final FunctionDescriptor BN_BLINDING_create_param$bn_mod_exp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_BLINDING_create_param$bn_mod_exp$MH = RuntimeHelper.downcallHandle(
        constants$169.BN_BLINDING_create_param$bn_mod_exp$FUNC, false
    );
    static final FunctionDescriptor BN_BLINDING_create_param$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_BLINDING_create_param$MH = RuntimeHelper.downcallHandle(
        "BN_BLINDING_create_param",
        constants$169.BN_BLINDING_create_param$FUNC, false
    );
    static final FunctionDescriptor BN_set_params$FUNC = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle BN_set_params$MH = RuntimeHelper.downcallHandle(
        "BN_set_params",
        constants$169.BN_set_params$FUNC, false
    );
    static final FunctionDescriptor BN_get_params$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle BN_get_params$MH = RuntimeHelper.downcallHandle(
        "BN_get_params",
        constants$169.BN_get_params$FUNC, false
    );
    static final FunctionDescriptor BN_RECP_CTX_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BN_RECP_CTX_new$MH = RuntimeHelper.downcallHandle(
        "BN_RECP_CTX_new",
        constants$169.BN_RECP_CTX_new$FUNC, false
    );
    static final FunctionDescriptor BN_RECP_CTX_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle BN_RECP_CTX_free$MH = RuntimeHelper.downcallHandle(
        "BN_RECP_CTX_free",
        constants$169.BN_RECP_CTX_free$FUNC, false
    );
}


