// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$120 {

    static final FunctionDescriptor BIO_next$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle BIO_next$MH = RuntimeHelper.downcallHandle(
        "BIO_next",
        constants$120.BIO_next$FUNC, false
    );
    static final FunctionDescriptor BIO_set_next$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BIO_set_next$MH = RuntimeHelper.downcallHandle(
        "BIO_set_next",
        constants$120.BIO_set_next$FUNC, false
    );
    static final FunctionDescriptor BIO_get_retry_BIO$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle BIO_get_retry_BIO$MH = RuntimeHelper.downcallHandle(
        "BIO_get_retry_BIO",
        constants$120.BIO_get_retry_BIO$FUNC, false
    );
    static final FunctionDescriptor BIO_get_retry_reason$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle BIO_get_retry_reason$MH = RuntimeHelper.downcallHandle(
        "BIO_get_retry_reason",
        constants$120.BIO_get_retry_reason$FUNC, false
    );
    static final FunctionDescriptor BIO_set_retry_reason$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle BIO_set_retry_reason$MH = RuntimeHelper.downcallHandle(
        "BIO_set_retry_reason",
        constants$120.BIO_set_retry_reason$FUNC, false
    );
    static final FunctionDescriptor BIO_dup_chain$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle BIO_dup_chain$MH = RuntimeHelper.downcallHandle(
        "BIO_dup_chain",
        constants$120.BIO_dup_chain$FUNC, false
    );
}


