// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$448 {

    static final FunctionDescriptor DH_security_bits$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DH_security_bits$MH = RuntimeHelper.downcallHandle(
        "DH_security_bits",
        constants$448.DH_security_bits$FUNC, false
    );
    static final FunctionDescriptor DH_set_ex_data$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DH_set_ex_data$MH = RuntimeHelper.downcallHandle(
        "DH_set_ex_data",
        constants$448.DH_set_ex_data$FUNC, false
    );
    static final FunctionDescriptor DH_get_ex_data$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle DH_get_ex_data$MH = RuntimeHelper.downcallHandle(
        "DH_get_ex_data",
        constants$448.DH_get_ex_data$FUNC, false
    );
    static final FunctionDescriptor DH_generate_parameters$callback$FUNC = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle DH_generate_parameters$callback$MH = RuntimeHelper.downcallHandle(
        constants$448.DH_generate_parameters$callback$FUNC, false
    );
    static final FunctionDescriptor DH_generate_parameters$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle DH_generate_parameters$MH = RuntimeHelper.downcallHandle(
        "DH_generate_parameters",
        constants$448.DH_generate_parameters$FUNC, false
    );
}


