// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$291 {

    static final FunctionDescriptor EVP_md5$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_md5$MH = RuntimeHelper.downcallHandle(
        "EVP_md5",
        constants$291.EVP_md5$FUNC, false
    );
    static final FunctionDescriptor EVP_md5_sha1$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_md5_sha1$MH = RuntimeHelper.downcallHandle(
        "EVP_md5_sha1",
        constants$291.EVP_md5_sha1$FUNC, false
    );
    static final FunctionDescriptor EVP_blake2b512$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_blake2b512$MH = RuntimeHelper.downcallHandle(
        "EVP_blake2b512",
        constants$291.EVP_blake2b512$FUNC, false
    );
    static final FunctionDescriptor EVP_blake2s256$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_blake2s256$MH = RuntimeHelper.downcallHandle(
        "EVP_blake2s256",
        constants$291.EVP_blake2s256$FUNC, false
    );
    static final FunctionDescriptor EVP_sha1$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_sha1$MH = RuntimeHelper.downcallHandle(
        "EVP_sha1",
        constants$291.EVP_sha1$FUNC, false
    );
    static final FunctionDescriptor EVP_sha224$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle EVP_sha224$MH = RuntimeHelper.downcallHandle(
        "EVP_sha224",
        constants$291.EVP_sha224$FUNC, false
    );
}


