// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$418 {

    static final FunctionDescriptor EC_KEY_METHOD_get_compute_key$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_get_compute_key$MH = RuntimeHelper.downcallHandle(
        "EC_KEY_METHOD_get_compute_key",
        constants$418.EC_KEY_METHOD_get_compute_key$FUNC, false
    );
    static final FunctionDescriptor EC_KEY_METHOD_get_sign$psign$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_get_sign$psign$MH = RuntimeHelper.downcallHandle(
        constants$418.EC_KEY_METHOD_get_sign$psign$FUNC, false
    );
    static final FunctionDescriptor EC_KEY_METHOD_get_sign$psign_setup$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EC_KEY_METHOD_get_sign$psign_setup$MH = RuntimeHelper.downcallHandle(
        constants$418.EC_KEY_METHOD_get_sign$psign_setup$FUNC, false
    );
    static final FunctionDescriptor EC_KEY_METHOD_get_sign$psign_sig$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
}


