// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$996 {

    static final FunctionDescriptor i2d_EDIPARTYNAME$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_EDIPARTYNAME$MH = RuntimeHelper.downcallHandle(
        "i2d_EDIPARTYNAME",
        constants$996.i2d_EDIPARTYNAME$FUNC, false
    );
    static final FunctionDescriptor OTHERNAME_cmp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle OTHERNAME_cmp$MH = RuntimeHelper.downcallHandle(
        "OTHERNAME_cmp",
        constants$996.OTHERNAME_cmp$FUNC, false
    );
    static final FunctionDescriptor GENERAL_NAME_set0_value$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle GENERAL_NAME_set0_value$MH = RuntimeHelper.downcallHandle(
        "GENERAL_NAME_set0_value",
        constants$996.GENERAL_NAME_set0_value$FUNC, false
    );
    static final FunctionDescriptor GENERAL_NAME_get0_value$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle GENERAL_NAME_get0_value$MH = RuntimeHelper.downcallHandle(
        "GENERAL_NAME_get0_value",
        constants$996.GENERAL_NAME_get0_value$FUNC, false
    );
    static final FunctionDescriptor GENERAL_NAME_set0_othername$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle GENERAL_NAME_set0_othername$MH = RuntimeHelper.downcallHandle(
        "GENERAL_NAME_set0_othername",
        constants$996.GENERAL_NAME_set0_othername$FUNC, false
    );
    static final FunctionDescriptor GENERAL_NAME_get0_otherName$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle GENERAL_NAME_get0_otherName$MH = RuntimeHelper.downcallHandle(
        "GENERAL_NAME_get0_otherName",
        constants$996.GENERAL_NAME_get0_otherName$FUNC, false
    );
}


