// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1174 {

    static final MemorySegment LN_pbeWithMD2AndDES_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pbeWithMD2AndDES-CBC");
    static final MemorySegment SN_pbeWithMD5AndDES_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PBE-MD5-DES");
    static final MemorySegment LN_pbeWithMD5AndDES_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pbeWithMD5AndDES-CBC");
    static final MemorySegment SN_pbeWithMD2AndRC2_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PBE-MD2-RC2-64");
    static final MemorySegment LN_pbeWithMD2AndRC2_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("pbeWithMD2AndRC2-CBC");
    static final MemorySegment SN_pbeWithMD5AndRC2_CBC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PBE-MD5-RC2-64");
}


