// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$727 {

    static final FunctionDescriptor i2d_PKCS8PrivateKey_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PKCS8PrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_PKCS8PrivateKey_bio",
        constants$727.i2d_PKCS8PrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_PKCS8PrivateKey_nid_bio$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PKCS8PrivateKey_nid_bio$MH = RuntimeHelper.downcallHandle(
        "i2d_PKCS8PrivateKey_nid_bio",
        constants$727.i2d_PKCS8PrivateKey_nid_bio$FUNC, false
    );
    static final FunctionDescriptor d2i_PKCS8PrivateKey_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PKCS8PrivateKey_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_PKCS8PrivateKey_bio",
        constants$727.d2i_PKCS8PrivateKey_bio$FUNC, false
    );
    static final FunctionDescriptor i2d_PKCS8PrivateKey_fp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PKCS8PrivateKey_fp$MH = RuntimeHelper.downcallHandle(
        "i2d_PKCS8PrivateKey_fp",
        constants$727.i2d_PKCS8PrivateKey_fp$FUNC, false
    );
    static final FunctionDescriptor i2d_PKCS8PrivateKey_nid_fp$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_PKCS8PrivateKey_nid_fp$MH = RuntimeHelper.downcallHandle(
        "i2d_PKCS8PrivateKey_nid_fp",
        constants$727.i2d_PKCS8PrivateKey_nid_fp$FUNC, false
    );
    static final FunctionDescriptor PEM_write_PKCS8PrivateKey_nid$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PEM_write_PKCS8PrivateKey_nid$MH = RuntimeHelper.downcallHandle(
        "PEM_write_PKCS8PrivateKey_nid",
        constants$727.PEM_write_PKCS8PrivateKey_nid$FUNC, false
    );
}


