// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$845 {

    static final FunctionDescriptor SSL_get_default_timeout$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle SSL_get_default_timeout$MH = RuntimeHelper.downcallHandle(
        "SSL_get_default_timeout",
        constants$845.SSL_get_default_timeout$FUNC, false
    );
    static final FunctionDescriptor SSL_CIPHER_description$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle SSL_CIPHER_description$MH = RuntimeHelper.downcallHandle(
        "SSL_CIPHER_description",
        constants$845.SSL_CIPHER_description$FUNC, false
    );
    static final FunctionDescriptor SSL_dup_CA_list$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_dup_CA_list$MH = RuntimeHelper.downcallHandle(
        "SSL_dup_CA_list",
        constants$845.SSL_dup_CA_list$FUNC, false
    );
    static final FunctionDescriptor SSL_dup$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_dup$MH = RuntimeHelper.downcallHandle(
        "SSL_dup",
        constants$845.SSL_dup$FUNC, false
    );
    static final FunctionDescriptor SSL_get_certificate$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_get_certificate$MH = RuntimeHelper.downcallHandle(
        "SSL_get_certificate",
        constants$845.SSL_get_certificate$FUNC, false
    );
    static final FunctionDescriptor SSL_get_privatekey$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle SSL_get_privatekey$MH = RuntimeHelper.downcallHandle(
        "SSL_get_privatekey",
        constants$845.SSL_get_privatekey$FUNC, false
    );
}


