// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$379 {

    static final FunctionDescriptor EVP_PKEY_meth_get_ctrl$pctrl_str$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_ctrl$pctrl_str$MH = RuntimeHelper.downcallHandle(
        constants$379.EVP_PKEY_meth_get_ctrl$pctrl_str$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_ctrl$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_ctrl$MH = RuntimeHelper.downcallHandle(
        "EVP_PKEY_meth_get_ctrl",
        constants$379.EVP_PKEY_meth_get_ctrl$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_digestsign$digestsign$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle EVP_PKEY_meth_get_digestsign$digestsign$MH = RuntimeHelper.downcallHandle(
        constants$379.EVP_PKEY_meth_get_digestsign$digestsign$FUNC, false
    );
    static final FunctionDescriptor EVP_PKEY_meth_get_digestsign$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle EVP_PKEY_meth_get_digestsign$MH = RuntimeHelper.downcallHandle(
        "EVP_PKEY_meth_get_digestsign",
        constants$379.EVP_PKEY_meth_get_digestsign$FUNC, false
    );
}


