// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface dynamic_v_check_fn {

    long apply(long x0);
    static CLinker.UpcallStub allocate(dynamic_v_check_fn fi) {
        return RuntimeHelper.upcallStub(dynamic_v_check_fn.class, fi, constants$1116.dynamic_v_check_fn$FUNC, "(J)J");
    }
    static CLinker.UpcallStub allocate(dynamic_v_check_fn fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(dynamic_v_check_fn.class, fi, constants$1116.dynamic_v_check_fn$FUNC, "(J)J", scope);
    }
    static dynamic_v_check_fn ofAddress(MemoryAddress addr) {
        return (long x0) -> {
            try {
                return (long)constants$1116.dynamic_v_check_fn$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


