// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class EDIPartyName_st {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withName("nameAssigner"),
        ADDRESS.withName("partyName")
    ).withName("EDIPartyName_st");
    public static MemoryLayout $LAYOUT() {
        return EDIPartyName_st.$struct$LAYOUT;
    }
    static final VarHandle nameAssigner$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("nameAssigner"));
    public static VarHandle nameAssigner$VH() {
        return EDIPartyName_st.nameAssigner$VH;
    }
    public static MemoryAddress nameAssigner$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)EDIPartyName_st.nameAssigner$VH.get(seg);
    }
    public static void nameAssigner$set( MemorySegment seg, MemoryAddress x) {
        EDIPartyName_st.nameAssigner$VH.set(seg, x);
    }
    public static MemoryAddress nameAssigner$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)EDIPartyName_st.nameAssigner$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void nameAssigner$set(MemorySegment seg, long index, MemoryAddress x) {
        EDIPartyName_st.nameAssigner$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle partyName$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("partyName"));
    public static VarHandle partyName$VH() {
        return EDIPartyName_st.partyName$VH;
    }
    public static MemoryAddress partyName$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)EDIPartyName_st.partyName$VH.get(seg);
    }
    public static void partyName$set( MemorySegment seg, MemoryAddress x) {
        EDIPartyName_st.partyName$VH.set(seg, x);
    }
    public static MemoryAddress partyName$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)EDIPartyName_st.partyName$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void partyName$set(MemorySegment seg, long index, MemoryAddress x) {
        EDIPartyName_st.partyName$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


