// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface ENGINE_GEN_FUNC_PTR {

    int apply();
    static CLinker.UpcallStub allocate(ENGINE_GEN_FUNC_PTR fi) {
        return RuntimeHelper.upcallStub(ENGINE_GEN_FUNC_PTR.class, fi, constants$1091.ENGINE_GEN_FUNC_PTR$FUNC, "()I");
    }
    static CLinker.UpcallStub allocate(ENGINE_GEN_FUNC_PTR fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(ENGINE_GEN_FUNC_PTR.class, fi, constants$1091.ENGINE_GEN_FUNC_PTR$FUNC, "()I", scope);
    }
    static ENGINE_GEN_FUNC_PTR ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                return (int)constants$1091.ENGINE_GEN_FUNC_PTR$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


