// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface ENGINE_ctrl_cmd$f {

    void apply();
    static CLinker.UpcallStub allocate(ENGINE_ctrl_cmd$f fi) {
        return RuntimeHelper.upcallStub(ENGINE_ctrl_cmd$f.class, fi, constants$1101.ENGINE_ctrl_cmd$f$FUNC, "()V");
    }
    static CLinker.UpcallStub allocate(ENGINE_ctrl_cmd$f fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(ENGINE_ctrl_cmd$f.class, fi, constants$1101.ENGINE_ctrl_cmd$f$FUNC, "()V", scope);
    }
    static ENGINE_ctrl_cmd$f ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                constants$1102.ENGINE_ctrl_cmd$f$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


