// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface EVP_MD_meth_set_cleanup$cleanup {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static NativeSymbol allocate(EVP_MD_meth_set_cleanup$cleanup fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(EVP_MD_meth_set_cleanup$cleanup.class, fi, constants$263.EVP_MD_meth_set_cleanup$cleanup$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static EVP_MD_meth_set_cleanup$cleanup ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("EVP_MD_meth_set_cleanup$cleanup::" + Long.toHexString(addr.toRawLongValue()), addr, scope);return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$264.EVP_MD_meth_set_cleanup$cleanup$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


