// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class IPAddressOrRange_st {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(32),
        MemoryLayout.unionLayout(
            ADDRESS.withName("addressPrefix"),
            ADDRESS.withName("addressRange")
        ).withName("u")
    ).withName("IPAddressOrRange_st");
    public static MemoryLayout $LAYOUT() {
        return IPAddressOrRange_st.$struct$LAYOUT;
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return IPAddressOrRange_st.type$VH;
    }
    public static int type$get(MemorySegment seg) {
        return (int)IPAddressOrRange_st.type$VH.get(seg);
    }
    public static void type$set( MemorySegment seg, int x) {
        IPAddressOrRange_st.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)IPAddressOrRange_st.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        IPAddressOrRange_st.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static class u {

        static final MemoryLayout u$union$LAYOUT = MemoryLayout.unionLayout(
            ADDRESS.withName("addressPrefix"),
            ADDRESS.withName("addressRange")
        );
        public static MemoryLayout $LAYOUT() {
            return u.u$union$LAYOUT;
        }
        static final VarHandle addressPrefix$VH = u$union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("addressPrefix"));
        public static VarHandle addressPrefix$VH() {
            return u.addressPrefix$VH;
        }
        public static MemoryAddress addressPrefix$get(MemorySegment seg) {
            return (jdk.incubator.foreign.MemoryAddress)u.addressPrefix$VH.get(seg);
        }
        public static void addressPrefix$set( MemorySegment seg, MemoryAddress x) {
            u.addressPrefix$VH.set(seg, x);
        }
        public static MemoryAddress addressPrefix$get(MemorySegment seg, long index) {
            return (jdk.incubator.foreign.MemoryAddress)u.addressPrefix$VH.get(seg.asSlice(index*sizeof()));
        }
        public static void addressPrefix$set(MemorySegment seg, long index, MemoryAddress x) {
            u.addressPrefix$VH.set(seg.asSlice(index*sizeof()), x);
        }
        static final VarHandle addressRange$VH = u$union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("addressRange"));
        public static VarHandle addressRange$VH() {
            return u.addressRange$VH;
        }
        public static MemoryAddress addressRange$get(MemorySegment seg) {
            return (jdk.incubator.foreign.MemoryAddress)u.addressRange$VH.get(seg);
        }
        public static void addressRange$set( MemorySegment seg, MemoryAddress x) {
            u.addressRange$VH.set(seg, x);
        }
        public static MemoryAddress addressRange$get(MemorySegment seg, long index) {
            return (jdk.incubator.foreign.MemoryAddress)u.addressRange$VH.get(seg.asSlice(index*sizeof()));
        }
        public static void addressRange$set(MemorySegment seg, long index, MemoryAddress x) {
            u.addressRange$VH.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
        public static MemorySegment allocateArray(int len, ResourceScope scope) {
            return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
        }
        public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
    }

    public static MemorySegment u$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


