// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface lh_OPENSSL_STRING_new$hfn {

    long apply(jdk.incubator.foreign.MemoryAddress x0);
    static CLinker.UpcallStub allocate(lh_OPENSSL_STRING_new$hfn fi) {
        return RuntimeHelper.upcallStub(lh_OPENSSL_STRING_new$hfn.class, fi, constants$530.lh_OPENSSL_STRING_new$hfn$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)J");
    }
    static CLinker.UpcallStub allocate(lh_OPENSSL_STRING_new$hfn fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(lh_OPENSSL_STRING_new$hfn.class, fi, constants$530.lh_OPENSSL_STRING_new$hfn$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)J", scope);
    }
    static lh_OPENSSL_STRING_new$hfn ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (long)constants$531.lh_OPENSSL_STRING_new$hfn$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


