// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class PBEPARAM_st {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withName("salt"),
        ADDRESS.withName("iter")
    ).withName("PBEPARAM_st");
    public static MemoryLayout $LAYOUT() {
        return PBEPARAM_st.$struct$LAYOUT;
    }
    static final VarHandle salt$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("salt"));
    public static VarHandle salt$VH() {
        return PBEPARAM_st.salt$VH;
    }
    public static MemoryAddress salt$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)PBEPARAM_st.salt$VH.get(seg);
    }
    public static void salt$set( MemorySegment seg, MemoryAddress x) {
        PBEPARAM_st.salt$VH.set(seg, x);
    }
    public static MemoryAddress salt$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)PBEPARAM_st.salt$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void salt$set(MemorySegment seg, long index, MemoryAddress x) {
        PBEPARAM_st.salt$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle iter$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("iter"));
    public static VarHandle iter$VH() {
        return PBEPARAM_st.iter$VH;
    }
    public static MemoryAddress iter$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)PBEPARAM_st.iter$VH.get(seg);
    }
    public static void iter$set( MemorySegment seg, MemoryAddress x) {
        PBEPARAM_st.iter$VH.set(seg, x);
    }
    public static MemoryAddress iter$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)PBEPARAM_st.iter$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void iter$set(MemorySegment seg, long index, MemoryAddress x) {
        PBEPARAM_st.iter$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


