// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface pthread_once$__init_routine {

    void apply();
    static CLinker.UpcallStub allocate(pthread_once$__init_routine fi) {
        return RuntimeHelper.upcallStub(pthread_once$__init_routine.class, fi, constants$86.pthread_once$__init_routine$FUNC, "()V");
    }
    static CLinker.UpcallStub allocate(pthread_once$__init_routine fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(pthread_once$__init_routine.class, fi, constants$86.pthread_once$__init_routine$FUNC, "()V", scope);
    }
    static pthread_once$__init_routine ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                constants$86.pthread_once$__init_routine$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


