// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface SSL_verify_cb {

    int apply(int x0, jdk.incubator.foreign.MemoryAddress x1);
    static NativeSymbol allocate(SSL_verify_cb fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(SSL_verify_cb.class, fi, constants$762.SSL_verify_cb$FUNC, "(ILjdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static SSL_verify_cb ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("SSL_verify_cb::" + Long.toHexString(addr.toRawLongValue()), addr, scope);return (int x0, jdk.incubator.foreign.MemoryAddress x1) -> {
            try {
                return (int)constants$763.SSL_verify_cb$MH.invokeExact(symbol, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


