// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface UI_method_set_flusher$flusher {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static CLinker.UpcallStub allocate(UI_method_set_flusher$flusher fi) {
        return RuntimeHelper.upcallStub(UI_method_set_flusher$flusher.class, fi, constants$1084.UI_method_set_flusher$flusher$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
    }
    static CLinker.UpcallStub allocate(UI_method_set_flusher$flusher fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(UI_method_set_flusher$flusher.class, fi, constants$1084.UI_method_set_flusher$flusher$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static UI_method_set_flusher$flusher ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$1084.UI_method_set_flusher$flusher$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


