// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface X509_LOOKUP_meth_set_shutdown$shutdown {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static NativeSymbol allocate(X509_LOOKUP_meth_set_shutdown$shutdown fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(X509_LOOKUP_meth_set_shutdown$shutdown.class, fi, constants$573.X509_LOOKUP_meth_set_shutdown$shutdown$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static X509_LOOKUP_meth_set_shutdown$shutdown ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("X509_LOOKUP_meth_set_shutdown$shutdown::" + Long.toHexString(addr.toRawLongValue()), addr, scope);return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$573.X509_LOOKUP_meth_set_shutdown$shutdown$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


